### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by kwz1993** [hhyo/archer#1183]
### 问题描述
docker 版本升级 
1.7.11 升级至1.8.1 
升级步骤已按文档顺序执行：
在执行以下更新时，报错
Django和Django-q的版本升级涉及数据migrate，请在服务部署完成后执行 python manage.py migrate
报错内容：
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
[root@ce53f06e2bf9 archery]# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
[root@ce53f06e2bf9 archery]# source /opt/venv4archery/bin/activate
(venv4archery) [root@ce53f06e2bf9 archery]# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/migrations/loader.py", line 302, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration sql.0001_initial is applied before its dependency auth.0012_alter_user_first_name_max_length on database 'default'.

请问下，在刷新这个依赖报错，该怎么解决。

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
试试单独变更 python manage.py migrate django_q
