### ISSUE TITLE
[ 功能建议 ]LDAP中cn为中文时，默认配置会触发唯一键冲突错误

### ISSUE THREAD

**Issue by unknowissue** [hhyo/archer#1184]
您好
  很高兴使用Archery-1.8.1
### 目前遇到的问题/使用障碍
  我的LDAP配置中cn为中文名字，且settings.py 配置为
  ` 
    AUTH_LDAP_ALWAYS_UPDATE_USER = True  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "cn",
        "display": "displayname",
        "email": "mail"
`
  于是通过LDAP第一次登录后，sql_users.username 将会是中文
  第二次登录会提示内部错误 “Internal Server Error”
  后台报错
`[2021-09-17 19:08:39,739][MainThread:139636977768256][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/archery/Archery-1.8.1/common/auth.py", line 61, in authenticate
    user = Users.objects.get(username=username)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
sql.models.Users.DoesNotExist: Users matching query does not exist.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/archery/venv4archery/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/archery/venv4archery/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/archery/venv4archery/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '姓名' for key 'sql_users.username'")
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/archery/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/archery/Archery-1.8.1/common/auth.py", line 105, in authenticate_entry
    result = new_auth.authenticate()
  File "/archery/Archery-1.8.1/common/auth.py", line 63, in authenticate
    authenticated_user = self.challenge(username=username, password=password)
  File "/archery/Archery-1.8.1/common/auth.py", line 48, in challenge
    user = authenticate(username=username, password=password)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/archery/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 153, in authenticate
    else:
  File "/archery/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 211, in authenticate_ldap_user
  File "/archery/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 355, in authenticate
  File "/archery/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 632, in _get_or_create_user
  File "/archery/Archery-1.8.1/sql/models.py", line 50, in save
    super(Users, self).save(*args, **kwargs)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/archery/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/archery/venv4archery/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/archery/venv4archery/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/archery/venv4archery/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '姓名' for key 'sql_users.username'")`

  这个问题的解决方法是修改为其他的非中文唯一标识，这里我使用了 sAMAccountName 
`
 AUTH_LDAP_ALWAYS_UPDATE_USER = True  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "sAMAccountName",
        "display": "displayname",
        "email": "mail"

`
我建议在安装文档中增加对于此部分的说明。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
感谢提供解决办法，wiki开放编辑，欢迎补充
https://github.com/hhyo/archery/wiki/auth#%E9%9B%86%E6%88%90ldap

**Comment by fancy-lee** [comment]
不为中文也会报用户名冲突，我这边还会增加一个空格

**Comment by fancy-lee** [comment]
ldapsearch -x -H ldap://127.0.0.1:389 -b "dc=baidu,dc=com" -D "cn=admin,dc=baidu,dc=com" -w baidu  #注意：命令中的选项替换成你自己的配置
解决方法：用上面的命令查看一下有什么字段可以替换的，我用cn也不行同时也不是中文的，换了一个别的字段就没有问题了

**Comment by fancy-lee** [comment]
我遇到还有一个问题就是使用TLS的636端口也会有问题，不用带TLS的端口就正常

**Comment by fancy-lee** [comment]
sAMAccountName 这个字段应该是你们公司自己定的，其它公司不一定有

**Comment by unknowissue** [comment]
> sAMAccountName 这个字段应该是你们公司自己定的，其它公司不一定有

不，应该都有的
请参考
https://ldapwiki.com/wiki/SamAccountName
https://stackoverflow.com/questions/508014/active-directory-ldap-query-by-samaccountname-and-domain

**Comment by unknowissue** [comment]
> 感谢提供解决办法，wiki开放编辑，欢迎补充

已补充

**Comment by fancy-lee** [comment]
> > sAMAccountName 这个字段应该是你们公司自己定的，其它公司不一定有
> 
> 不，应该都有的 请参考 https://ldapwiki.com/wiki/SamAccountName https://stackoverflow.com/questions/508014/active-directory-ldap-query-by-samaccountname-and-domain

我们公司的openldap就没有这个字段
