### ISSUE TITLE
[ 问题咨询 ] ldap配置后能登录，但是左侧菜单看不到

### ISSUE THREAD

**Issue by ccwall3** [hhyo/archer#1233]
用的是© Archery (v1.8.1)

log信息：
[2021-11-16 15:48:35,000][MainThread:139929637947200][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied

[2021-11-16 15:49:48,465][MainThread:139929637947200][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
[2021-11-16 15:49:49,826][MainThread:139929637947200][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied

![image](https://user-images.githubusercontent.com/7711718/141943855-03a98a5b-5749-4e42-a19d-e8816df242b6.png)

![image](https://user-images.githubusercontent.com/7711718/141943980-0d5df19c-411c-4497-80bf-f6c89edf6af8.png)

**Comment by peng19832** [comment]
要配菜单权限，人员要关联权限组或者权限
![image](https://user-images.githubusercontent.com/9590209/141952397-40fabd7f-7af1-4c4e-871f-a8ea4ab2b0fd.png)
