### ISSUE TITLE
[ 问题咨询 ]ORACLE的sql审核报错ORA-00604 ORA-25153

### ISSUE THREAD

**Issue by sjf2303** [hhyo/archer#1236]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

测试oracle数据库sql上线审核，一直报ORA-00604: error occurred at recursive SQL level 1
                                                              ORA-25153: Temporary Tablespace is Empty
用plsql执行sql正常。mysql功能正常
sql如下：
create table classinfo(
       id number(2) primary key,
       name varchar(10) not null       
       );
审核/执行信息：
'stmt_type' : Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/opt/archery/sql/utils/execute_sql.py", line 35, in execute
return execute_engine.execute_workflow(workflow=workflow_detail)
File "/opt/archery/sql/engines/oracle.py", line 612, in execute_workflow
sqlitemList = get_exec_sqlitem_list(review_result, workflow.db_name)
File "/opt/archery/sql/utils/sql_utils.py", line 300, in get_exec_sqlitem_list
stmt_type=item['stmt_type'],
KeyError: 'stmt_type'
### 版本信息
 - 应用版本/分支：Release v1.8.1  
 - 部署方式：docker；mysql和redis非docker

**Comment by e71hao** [comment]
@hhyo  小圈圈，你好！  我们也是遇到同样的问题：只要sql检测错误，继续提交工单，审批通过，立即执行，就会报错：stmt_type : Traceback 。
这个错误的复现要这样：
1. 设置AUTO_REVIEW_WRONG为3，表示SQL检测错误也不驳回。
2. 有一张表test2 (create table test2 (id int primary key ,name varchar2(100) ); ) .现在提一个SQL审核工单，工单内容是：给表test2增加一列，然后插入数据，sql检测会报ORA-00913: too many values.  因为我会先给表增加一列，此时列数刚好匹配，SQL执行不会有问题， 所以我仍然提交工单。
  alter table  test2 add  (age int) ; 
  insert into test2 values (2, 'test_name', 18) ; 
审批通过后我立即执行，会报错：
[2021-12-03 14:16:17,990][MainThread:139914921178944][task_id:django-q][cluster.py:390][ERROR]- Failed [sqlreview-execute-19] - 'stmt_type' : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/opt/archery/sql/utils/execute_sql.py", line 35, in execute
    return execute_engine.execute_workflow(workflow=workflow_detail)
  File "/opt/archery/sql/engines/oracle.py", line 612, in execute_workflow
    sqlitemList = get_exec_sqlitem_list(review_result, workflow.db_name)
  File "/opt/archery/sql/utils/sql_utils.py", line 300, in get_exec_sqlitem_list
    stmt_type=item['stmt_type'],
KeyError: 'stmt_type'
![image](https://user-images.githubusercontent.com/65882595/144558165-d1c479c9-7c6d-481b-bb1f-efcb6bbac106.png)

万望回复，谢谢

**Comment by hhyo** [comment]
> @hhyo 小圈圈，你好！ 我们也是遇到同样的问题：只要sql检测错误，继续提交工单，审批通过，立即执行，就会报错：stmt_type : Traceback 。 这个错误的复现要这样：
> 
> 1. 设置AUTO_REVIEW_WRONG为3，表示SQL检测错误也不驳回。
> 2. 有一张表test2 (create table test2 (id int primary key ,name varchar2(100) ); ) .现在提一个SQL审核工单，工单内容是：给表test2增加一列，然后插入数据，sql检测会报ORA-00913: too many values.  因为我会先给表增加一列，此时列数刚好匹配，SQL执行不会有问题， 所以我仍然提交工单。
>    alter table  test2 add  (age int) ;
>    insert into test2 values (2, 'test_name', 18) ;
>    审批通过后我立即执行，会报错：
>    [2021-12-03 14:16:17,990][MainThread:139914921178944][task_id:django-q][cluster.py:390][ERROR]- Failed [sqlreview-execute-19] - 'stmt_type' : Traceback (most recent call last):
>    File "/opt/venv4archery/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
>    res = f(*task["args"], **task["kwargs"])
>    File "/opt/archery/sql/utils/execute_sql.py", line 35, in execute
>    return execute_engine.execute_workflow(workflow=workflow_detail)
>    File "/opt/archery/sql/engines/oracle.py", line 612, in execute_workflow
>    sqlitemList = get_exec_sqlitem_list(review_result, workflow.db_name)
>    File "/opt/archery/sql/utils/sql_utils.py", line 300, in get_exec_sqlitem_list
>    stmt_type=item['stmt_type'],
>    KeyError: 'stmt_type'
>    ![image](https://user-images.githubusercontent.com/65882595/144558165-d1c479c9-7c6d-481b-bb1f-efcb6bbac106.png)
> 
> 万望回复，谢谢

oracle审核没有处理这种混合的场景，建议分开进行提交
