### ISSUE TITLE
[ bug ] Gateway Time-out

### ISSUE THREAD

**Issue by arz-GW** [hhyo/archer#1254]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
版本 V1.8.1
安装方法 docker-compose
 执行时间超过60秒 会提示Gateway Time-out (我链接的是阿里rds数据库)
ps: 执行不超过60秒的SQL能顺利运行， MAX_EXECUTION_TIME 设置小于60是也能接到运行超时的报错
-->

### 期待结果和实际结果
期待结果：
设置MAX_EXECUTION_TIME 后， 在线查询的时间能和设置的一样
实际结果:

### 截图

![image](https://user-images.githubusercontent.com/46097927/143852792-60128b09-93e2-4212-bc6f-7ea62b4b9152.png)

 
### 错误日志

<!--请务必查看相关错误日志并贴出（这很关键），查看方式
```
/logs/archery.log
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (3024, 'Query execution was interrupted, maximum statement execution time exceeded')


/logs/qcluster.log
/logs/soar.log
docker logs archery -f --tail=10
````
where
  b.channelcode = 'carmum20210601'
  and a.create_time >= '2021-09-01 00:00:00'
  and a.create_time <= '2021-09-31 23:59:59'
  and a.ecsid not in (
    'U202001011133',
    'U2020010101321509',
    'U2007021016237efa72',
    'U20081211093332da25',
    'U2106081056a7ace3b7',
    '18921171009'
  )
order by
  a.ecsid,
  a.create_time limit 100;，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (3024, 'Query execution was interrupted, maximum statement execution time exceeded')
```
-->
### 版本信息
应用版本/分支：

部署方式：Docker

<!--
一般建议使用release版本，其他都是非稳定版本
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker、手工部署
-->

**Comment by arz-GW** [comment]
MAX_EXECUTION_TIME 不生效

**Comment by arz-GW** [comment]
修改MAX_EXECUTION_TIME  和 docker-compose 中的timeout 都没有用

**Comment by hhyo** [comment]
请检查Nginx的超时配置

**Comment by arz-GW** [comment]
nginx超时配置已设置但是还是超过60秒   timeout
![图片](https://user-images.githubusercontent.com/46097927/146116878-3f63288e-cfe2-4007-a172-62dd410a6be9.png)

**Comment by hhyo** [comment]
确认外层是否还有代理
