### ISSUE TITLE
[ bug ] 获取大数据量回滚sql时报memory error

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1318]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
对一个update了118万行数据的sql，查看其回滚sql，页面上无法加载出来，后台日志报memory error
![image](https://user-images.githubusercontent.com/9590209/148497950-cd193a57-7b44-4e70-990a-a794c983fbff.png)

### 期待结果和实际结果
期待结果：
可以获取回滚sql，或者可以下载

实际结果:
![image](https://user-images.githubusercontent.com/9590209/148498102-44894e80-673b-4927-abfb-2967c7a5ba2b.png)

[2022-01-07 11:07:09,960][MainThread:139934323099456][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/views.py", line 195, in rollback
    f.write(f'/*{sql[0]}*/\n{sql[1]}\n')
MemoryError

[2022-01-07 11:07:32,453][MainThread:139934323099456][task_id:default][inception.py:226][ERROR]- 获取回滚语句报错，异常信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/inception.py", line 224, in get_rollback
    list_backup_sql.append([sql, '\n'.join([back_info[0] for back_info in list_backup])])
MemoryError

[2022-01-07 13:46:21,271][MainThread:139934323099456][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/views.py", line 195, in rollback
    f.write(f'/*{sql[0]}*/\n{sql[1]}\n')
MemoryError

### 版本信息
应用版本/分支：1.8.1

**Comment by hhyo** [comment]
过于大了，可采取和binlog解析类似的方式，先临时存储到本地再下载
