### ISSUE TITLE
使用超管登录报403 Forbidden

### ISSUE THREAD

**Issue by yidazhi** [hhyo/archer#1361]
### 问题描述
添加实例等操作，通过Django管理,使用admin登录，报403 Forbidden

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：手工部署

![image](https://user-images.githubusercontent.com/35521643/151107681-edaff6f7-e7d5-4605-b845-0cb0fbef285a.png)

[2022-01-26 13:24:11,628][ThreadPoolExecutor-0_0:140213924890368][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 330, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1551, in _changeform_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied

请帮忙看下是什么问题

**Comment by LeoQuote** [comment]
手工部署的太复杂了没法支持啊, 你再提供多一些细节

**Comment by yidazhi** [comment]
有人把超管权限禁了，抱歉，打扰
