### ISSUE TITLE
[ docker部署时出错 ]mysql编码的问题

### ISSUE THREAD

**Issue by LYPvvvLYP** [hhyo/archer#1374]
### 问题描述
按照文档上的步骤，到 python3 manage.py migrate 时报 Incorrect string value: '\\xE6\\x85\\xA2\\xE6\\x97\\xA5...

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：Docker

```
(venv4archery) [root@80f6fcb4b596 archery]# python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_q, sessions, sql
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xE6\\x85\\xA2\\xE6\\x97\\xA5...' for column 'na      me' at row 1")
```

**Comment by LYPvvvLYP** [comment]
archery库下的表都是latin1，我再看会

**Comment by LYPvvvLYP** [comment]
解决了，手动修改了所有编码。
不知道为什么一开始是latin1

**Comment by michael-liumh** [comment]
默认的数据库编码就是 latin1

**Comment by michael-liumh** [comment]
你要在 mysql/my.cnf 文件里加一条 ```character_set_server   = utf8mb4 ```就ok了

**Comment by LYPvvvLYP** [comment]
你们的my.cnf文件里不是已经有了吗
![image](https://user-images.githubusercontent.com/28222117/155974849-17b60960-a8ef-4530-a72c-52c605ba1a65.png)

**Comment by ly520** [comment]
> 你要在 mysql/my.cnf 文件里加一条 `character_set_server = utf8mb4 `就ok了

这种方法我试过，并没有用

**Comment by davy-gan** [comment]
character-set-server = utf8mb4     和character_set_server = utf8mb4   有什么区别  我用1.13 版本生产的表都是latin1
