### ISSUE TITLE
[ 问题咨询 ]配置完数据库实例，测试链接成功后，进行SQL上线提交报错

### ISSUE THREAD

**Issue by wushuigen** [hhyo/archer#1377]
### 问题描述
1、配置完成后，增加数据库实例配置并测试链接成功
2、在SQL审核，SQL上线菜单中增加SQL上线，选择完资源组后进行数据库实例选择出现如下报错
![image](https://user-images.githubusercontent.com/47021825/153830811-8973fc58-b1b4-4344-ace8-2cc90b7b79e2.png)

后台没有相应的报错日志信息

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by weideguo** [comment]
打开浏览器的控制台看看具体哪个请求报错把？
这个系统最好不要对外网开放吧？如果实在有必要，也尽量使用https。以及在这里截图要给ip打码吧。

**Comment by wushuigen** [comment]
![image](https://user-images.githubusercontent.com/47021825/154207882-86957ffa-fa7e-426c-91f2-06ccb2c8ef05.png)

请求报错的接口地址如下：http://域名地址/instance/instance_resource/?instance_name=EJIUQIAO_DEV&resource_type=database

**Comment by weideguo** [comment]
运行时使用这个命令看看容器的日志 `docker logs --tail 10 -f  <容器id>`。
另外这个截图还是有ip泄露。

**Comment by wushuigen** [comment]
![image](https://user-images.githubusercontent.com/47021825/154208082-35ea1e85-1296-4bb3-9c2b-cf6860b73f9f.png)
日志没有找到对应的错误

**Comment by wushuigen** [comment]
![image](https://user-images.githubusercontent.com/47021825/154208258-fa3416e1-3fed-46f6-bddf-3706edc3631e.png)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/middleware/cache.py", line 145, in process_request
    cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/cache.py", line 360, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/opt/venv4archery/lib/python3.8/site-packages/django_redis/cache.py", line 87, in get
    value = self._get(key, default, version, client)
  File "/opt/venv4archery/lib/python3.8/site-packages/django_redis/cache.py", line 34, in _decorator
    raise e.__cause__
  File "/opt/venv4archery/lib/python3.8/site-packages/django_redis/client/default.py", line 220, in get
    value = client.get(key)
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/opt/venv4archery/lib/python3.8/site-packages/redis/connection.py", line 340, in read_response
    raise error
redis.exceptions.AuthenticationError: invalid password

没有找到对应报错匹配的日志啊
在实例管理中是可以找到对应的数据库的
![image](https://user-images.githubusercontent.com/47021825/154208620-8a57414c-b890-447c-a4f5-05985b8ede10.png)

**Comment by wushuigen** [comment]
找到问题了，其实是那个日志报错的问题，只是我自己认为这个不相关。已经改好了
