### ISSUE TITLE
[ 问题咨询 ]mongodb不能查询admin库之外的库表，Authentication failed., full error

### ISSUE THREAD

**Issue by Myshiner** [hhyo/archer#1396]
### 问题描述
1.查询一个表的数据时，报错
![image](https://user-images.githubusercontent.com/48242833/155105201-8e7b46f2-4cb4-44b8-9fbc-806cd1136e86.png)
2.还有就是没有库表的查询权限
![image](https://user-images.githubusercontent.com/48242833/155105560-c2b86d78-f128-42dc-a48f-cf1732c3dbba.png)
但是提交申请的时候报错

### 版本信息
 - 应用版本/分支：Release v1.8.2 
 - 部署方式：Docker

**Comment by nick2wang** [comment]
把两个错误的日志发上来看下
`docker logs archery -f`

**Comment by Myshiner** [comment]
[2022-02-23 09:38:36,039][MainThread:139984038930240][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：show slave status，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1227, 'Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation')

[2022-02-23 09:38:36,040][MainThread:139984038930240][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：select user_id,uname from user_info where id=1 limit -1;，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1")

**Comment by Myshiner** [comment]
[2022-02-23 09:38:36,039][MainThread:139984038930240][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：show slave status，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1227, 'Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation')

[2022-02-23 09:38:36,040][MainThread:139984038930240][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：select user_id,uname from user_info where id=1 limit -1;，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1")

**Comment by Myshiner** [comment]
我的sql是select  user_id,uname from user_info where id=1, 但是透传的时候就变成了 select  user_id,uname from user_info where id=1 limit -1所以会报错，另外看日志上只读查询为啥还要show slave status，还报错(1227, 'Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation')

**Comment by Myshiner** [comment]
另外，我点“SQL分析菜单”的时候也报错
[2022-02-23 09:49:42,094][MainThread:139984038930240][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied

**Comment by Myshiner** [comment]
上线工单那，工单执行后想看回滚语句报

[2022-02-23 10:05:57,390][MainThread:139984038930240][task_id:default][inception.py:226][ERROR]- 获取回滚语句报错，异常信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/inception.py", line 213, in get_rollback
    cur.execute(sql_table)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table '192_168_56_10_4401_qa.$_$Inception_backup_information$_$' doesn't exist")
是我设置的备份地址不对吗，必须要设置为docker的mysql地址吗，我设置的是外部的一个实例，但是我看回滚信息在docker 的mysql里面是有的

**Comment by nick2wang** [comment]
> 我的sql是select user_id,uname from user_info where id=1, 但是透传的时候就变成了 select user_id,uname from user_info where id=1 limit -1所以会报错，另外看日志上只读查询为啥还要show slave status，还报错(1227, 'Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation')

1.看下申请查询权限时选择的限制行数是多少
2.MySQLdb模块和goinception需要用到复制权限，如果有用到上线功能的话最好把权限给大些

**Comment by nick2wang** [comment]
> 另外，我点“SQL分析菜单”的时候也报错 [2022-02-23 09:49:42,094][MainThread:139984038930240][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last): File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view if test_func(request.user): File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms raise PermissionDenied django.core.exceptions.PermissionDenied

这个是权限问题，后台授权下这个菜单功能

**Comment by nick2wang** [comment]
> 上线工单那，工单执行后想看回滚语句报
> 
> [2022-02-23 10:05:57,390][MainThread:139984038930240][task_id:default][inception.py:226][ERROR]- 获取回滚语句报错，异常信息Traceback (most recent call last): File "/opt/archery/sql/engines/inception.py", line 213, in get_rollback cur.execute(sql_table) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query _mysql.connection.query(self, query) MySQLdb._exceptions.ProgrammingError: (1146, "Table '192_168_56_10_4401_qa.$_$Inception_backup_information$_$' doesn't exist") 是我设置的备份地址不对吗，必须要设置为docker的mysql地址吗，我设置的是外部的一个实例，但是我看回滚信息在docker 的mysql里面是有的

备份库可以与archery库分开，在配置项里设置了还要在inception配置文件里配置，默认是配置到docker mysql的，要改下
https://github.com/hhyo/Archery/blob/1cbd9ddb2165481cc7089bb5dfb7abba6f405375/src/docker-compose/inception/config.toml#L66-L69

**Comment by Myshiner** [comment]
上线工单那，工单执行后想看回滚语句报

[2022-02-23 10:05:57,390][MainThread:139984038930240][task_id:default][inception.py:226][ERROR]- 获取回滚语句报错，异常信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/inception.py", line 213, in get_rollback
    cur.execute(sql_table)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table '192_168_56_10_4401_qa.$_$Inception_backup_information$_$' doesn't exist")
是我设置的备份地址不对吗，必须要设置为docker的mysql地址吗，我设置的是外部的一个实例，但是我看回滚信息在docker 的mysql里面是有的

**Comment by nick2wang** [comment]
> > 上线工单那，工单执行后想看回滚语句报
> > [2022-02-23 10:05:57,390][MainThread:139984038930240][task_id:default][inception.py:226][ERROR]- 获取回滚语句报错，异常信息Traceback (most recent call last): File "/opt/archery/sql/engines/inception.py", line 213, in get_rollback cur.execute(sql_table) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query _mysql.connection.query(self, query) MySQLdb._exceptions.ProgrammingError: (1146, "Table '192_168_56_10_4401_qa.$_$Inception_backup_information$_$' doesn't exist") 是我设置的备份地址不对吗，必须要设置为docker的mysql地址吗，我设置的是外部的一个实例，但是我看回滚信息在docker 的mysql里面是有的
> 
> 备份库可以与archery库分开，在配置项里设置了还要在inception配置文件里配置，默认是配置到docker mysql的，要改下
> 
> https://github.com/hhyo/Archery/blob/1cbd9ddb2165481cc7089bb5dfb7abba6f405375/src/docker-compose/inception/config.toml#L66-L69

确认配置项和config.toml是否配置了同一个备份库信息

**Comment by Myshiner** [comment]
> > 上线工单那，工单执行后想看回滚语句报
> > [2022-02-23 10:05:57,390][MainThread:139984038930240][task_id:default][inception.py:226][ERROR]- 获取回滚语句报错，异常信息Traceback (most recent call last): File "/opt/archery/sql/engines/inception.py", line 213, in get_rollback cur.execute(sql_table) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query _mysql.connection.query(self, query) MySQLdb._exceptions.ProgrammingError: (1146, "Table '192_168_56_10_4401_qa.$_$Inception_backup_information$_$' doesn't exist") 是我设置的备份地址不对吗，必须要设置为docker的mysql地址吗，我设置的是外部的一个实例，但是我看回滚信息在docker 的mysql里面是有的
> 
> 备份库可以与archery库分开，在配置项里设置了还要在inception配置文件里配置，默认是配置到docker mysql的，要改下
> 
> https://github.com/hhyo/Archery/blob/1cbd9ddb2165481cc7089bb5dfb7abba6f405375/src/docker-compose/inception/config.toml#L66-L69

谢谢，这个可以了

**Comment by Myshiner** [comment]
关于mongodb的查询，也是报认证权限错误，但是实际用该账号去库里查没问题，配置的是dba权限用户
![image](https://user-images.githubusercontent.com/48242833/155268561-fdbc7a33-6fec-4734-a55f-2ffa6492df27.png)

docker日志报错如下：
[2022-02-23 13:47:57,173][MainThread:139984038930240][task_id:default][query.py:169][ERROR]- 查询异常报错，查询语句：db.Order.find()
，错误信息：Traceback (most recent call last):
  File "/opt/archery/sql/query.py", line 87, in query
    query_engine.get_connection(db_name=db_name)
  File "/opt/archery/sql/engines/mongo.py", line 510, in get_connection
    self.conn[self.db_name].authenticate(self.user, self.password, self.db_name)
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/database.py", line 1492, in authenticate
    self.client._cache_credentials(
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/mongo_client.py", line 781, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/pool.py", line 810, in authenticate
    auth.authenticate(credentials, self)
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/auth.py", line 673, in authenticate
    auth_func(credentials, sock_info)
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/auth.py", line 591, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/auth.py", line 295, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(
  File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response,
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

**Comment by nick2wang** [comment]
> 关于mongodb的查询，也是报认证权限错误，但是实际用该账号去库里查没问题，配置的是dba权限用户 ![image](https://user-images.githubusercontent.com/48242833/155268561-fdbc7a33-6fec-4734-a55f-2ffa6492df27.png)
> 
> docker日志报错如下： [2022-02-23 13:47:57,173][MainThread:139984038930240][task_id:default][query.py:169][ERROR]- 查询异常报错，查询语句：db.Order.find() ，错误信息：Traceback (most recent call last): File "/opt/archery/sql/query.py", line 87, in query query_engine.get_connection(db_name=db_name) File "/opt/archery/sql/engines/mongo.py", line 510, in get_connection self.conn[self.db_name].authenticate(self.user, self.password, self.db_name) File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/database.py", line 1492, in authenticate self.client._cache_credentials( File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/mongo_client.py", line 781, in _cache_credentials sock_info.authenticate(credentials) File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/pool.py", line 810, in authenticate auth.authenticate(credentials, self) File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/auth.py", line 673, in authenticate auth_func(credentials, sock_info) File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/auth.py", line 591, in _authenticate_default return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1') File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/auth.py", line 295, in _authenticate_scram res = sock_info.command(source, cmd) File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command return command(self, dbname, spec, slave_ok, File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/network.py", line 159, in command helpers._check_command_response( File "/opt/venv4archery/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response raise OperationFailure(msg % errmsg, code, response, pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

看下使用的是否是admin下的高权限账号，如果不是，跨库查询时需要在所有库创建相同账号

**Comment by Myshiner** [comment]
权限已经很高了，如下，还不够？
{
        "_id" : "admin.admindba",
        "userId" : UUID("e9c8d021-6c89-422f-9822-a948959bb3f2"),
        "user" : "admindba",
        "db" : "admin",
        "credentials" : {
                "SCRAM-SHA-1" : {
                        "iterationCount" : 10000,
                        "salt" : "UCrK/CKGutTL57nwCbnjqQ==",
                        "storedKey" : "kNq9Perlpp3NnM1ncG9gK4U7htQ=",
                        "serverKey" : "dMtoM8kjta3TfWbdWbKNh/eAVo4="
                },
                "SCRAM-SHA-256" : {
                        "iterationCount" : 15000,
                        "salt" : "yDJXpf1ioVc0sBefuO0Mx/Bt/s01RrhD6DNYoQ==",
                        "storedKey" : "HfArxrivRzL14otYpTtpPXjUwqxNzrGxRz3lgFN4sVY=",
                        "serverKey" : "EU8ppRmEkljZyVTBHlLL32Kcz5NHIkPd1SPTaFZJs0s="
                }
        },
        "roles" : [
                {
                        "role" : "userAdminAnyDatabase",
                        "db" : "admin"
                },
                {
                        "role" : "dbAdminAnyDatabase",
                        "db" : "admin"
                },
                {
                        "role" : "root",
                        "db" : "admin"
                },
                {
                        "role" : "readWriteAnyDatabase",
                        "db" : "admin"
                }
        ]
}

**Comment by Myshiner** [comment]
其实一般用户主要使用就三个功能：1. 提交上线sql(DDL/DML) 2. 只读查询 3. sql优化或者说评分(SOAR工具等)

**Comment by Myshiner** [comment]
我如果要单独使用上面的三个功能，分别都需要哪些权限呢，正常后台用户权限都会给足，就是archery权限那块太多了不知道怎么搞

**Comment by nick2wang** [comment]
> 我如果要单独使用上面的三个功能，分别都需要哪些权限呢，正常后台用户权限都会给足，就是archery权限那块太多了不知道怎么搞

这些就差不多了
![image](https://user-images.githubusercontent.com/33473924/155299075-ebc2418e-111c-4091-9ded-7862ed1ef2b9.png)

**Comment by Myshiner** [comment]
我新建了一个权限组给了您上面的所有权限，然后新建了一个用户到这个权限组，但是查询的时候仍然报没有库表的查询权限
![image](https://user-images.githubusercontent.com/48242833/155302101-7e97a91d-b719-4fbc-8ec5-9bfd2ab501b9.png)

**Comment by Myshiner** [comment]
还是少了哪一个权限
[2022-02-23 18:10:35,141][MainThread:139984038930240][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied

**Comment by hhyo** [comment]
https://archerydms.com/modules/query/

先看下文档

**Comment by Myshiner** [comment]
> https://archerydms.com/modules/query/
> 
> 先看下文档
文档我都看了
下面这些权限都给了，我觉得权限已经很大了啊，正常普通用户就是提交工单和查询，不能有执行权限的
sql|permission|菜单Dashboard
sql|permission|菜单SQL查询
sql|permission|菜单权限管理
sql|permission|菜单优化工具
sql|permission|菜单SQL分析
sql|permission|菜单SQL审核
sql|permission|菜单SQL优化
sql|permission|菜单在线查询
sql|permission|菜单SQL上线
sql|permission|执行SOAR
sql|permission|执行SQLAdvisor
sql|permission|执行SQLTuning
sql|permission|申请查询权限
sql|permission|提交SQL查询
sql|permission|执行SQL分析
sql|permission|提交SQL上线工单
sql|permission|管理查询权限
sql|permission|审核查询权限
sql|permission|审核SQL上线工单
sql|permission|可查询所在资源组内的所有实例

下面这两个不能给，普通用户只能提交变更工单和做只读查询，然后由DBA执行
执行上线工单(资源组粒度或者自己提交的)
可查询所有实例，这个要管理员去给，不同用户只能查询对应实例

**Comment by Myshiner** [comment]
> https://archerydms.com/modules/query/
> 
> 先看下文档
文档我都看了
下面这些权限都给了，我觉得权限已经很大了啊，正常普通用户就是提交工单和查询，不能有执行权限的
sql|permission|菜单Dashboard
sql|permission|菜单SQL查询
sql|permission|菜单权限管理
sql|permission|菜单优化工具
sql|permission|菜单SQL分析
sql|permission|菜单SQL审核
sql|permission|菜单SQL优化
sql|permission|菜单在线查询
sql|permission|菜单SQL上线
sql|permission|执行SOAR
sql|permission|执行SQLAdvisor
sql|permission|执行SQLTuning
sql|permission|申请查询权限
sql|permission|提交SQL查询
sql|permission|执行SQL分析
sql|permission|提交SQL上线工单
sql|permission|管理查询权限
sql|permission|审核查询权限
sql|permission|审核SQL上线工单
sql|permission|可查询所在资源组内的所有实例

下面这两个不能给，普通用户只能提交变更工单和做只读查询，然后由DBA执行
执行上线工单(资源组粒度或者自己提交的)
可查询所有实例，这个要管理员去给，不同用户只能查询对应实例

**Comment by Myshiner** [comment]
即使我用archery的admin用户去查询mongodb，也是报一样的认证错误，而且mongodb用户已经是root权限了

**Comment by Myshiner** [comment]
只能查mongodb下面admin库的，其他库的就不行

**Comment by nick2wang** [comment]
> 我新建了一个权限组给了您上面的所有权限，然后新建了一个用户到这个权限组，但是查询的时候仍然报没有库表的查询权限 ![image](https://user-images.githubusercontent.com/48242833/155302101-7e97a91d-b719-4fbc-8ec5-9bfd2ab501b9.png)

这个权限是archery层面控制的，并不是数据库层面的权限，这样才能实现archery配置一个数据库账号就可以分配给不同archery用户不同的查询权限，普通用户在archery查询之前都要在archery申请相应的查询权限

**Comment by nick2wang** [comment]
> 即使我用archery的admin用户去查询mongodb，也是报一样的认证错误，而且mongodb用户已经是root权限了

你的mongodb是什么版本的？

**Comment by Myshiner** [comment]
v1.8.2
我在issue里搜那个报错，有人好像遇到了，说修改mongo.py配置就可以，我修改了重启archery容器，还是一样

**Comment by nick2wang** [comment]
> v1.8.2 我在issue里搜那个报错，有人好像遇到了，说修改mongo.py配置就可以，我修改了重启archery容器，还是一样

不是archery，我是说你管理的mongo实例的版本号是多少

**Comment by nick2wang** [comment]
先拉下最新的 https://github.com/hhyo/Archery/blob/master/sql/engines/mongo.py 到你本地覆盖再看下有没有问题，我本地用最新代码不能复现你的问题

**Comment by Myshiner** [comment]
mongodb 5.0的，已经替换成最新的master分支mongo.py了，还是报相同错误

**Comment by nick2wang** [comment]
pymongo 3.12.0版本开始正式支持mongo 5.0，可能需要更新下依赖 @hhyo 
https://www.mongodb.com/community/forums/t/pymongo-3-12-0-released/115111

**Comment by nick2wang** [comment]
> mongodb 5.0的，已经替换成最新的master分支mongo.py了，还是报相同错误

1.实例列表点击测试看有没有报错？
2.实例配置数据库配置的什么？
![image](https://user-images.githubusercontent.com/33473924/155496709-a0899a44-0388-4545-80ff-e51c46fdd4d9.png)

**Comment by Myshiner** [comment]
实例配置的是admin库，连接测试是成功的

**Comment by Myshiner** [comment]
这个问题还可以解决吗？应该所有地方都可以复现的

**Comment by nick2wang** [comment]
> 这个问题还可以解决吗？应该所有地方都可以复现的

mongo这个我复现不了，加下wx吧，我帮你看下 wx: post-meridiem

**Comment by Aaron199** [comment]
mongodb我也遇到了类似的问题，经查看代码发现query.py在第87执行获取连接时，传入了查询的db_name，在mongo.py第505行get_connection方法内，db_name赋值给了MongoClient方法的authSource参数，此参数为mongo账号的认证库名称，如果账号不是在db_name内创建就会提示认证失败，解决方法可参考图2，在获取连接时不传输db_name, 那么mongo get_connection方法就可以使用创建实例时的数据库名称
图1，
![image](https://user-images.githubusercontent.com/35388612/161244294-ae21499c-5aad-4964-9823-7841b19939e5.png)
图2,
![image](https://user-images.githubusercontent.com/35388612/161245486-c6242a1d-cd44-4ea7-bf6d-b72b995c0a7c.png)

**Comment by weideguo** [comment]
> mongodb我也遇到了类似的问题，经查看代码发现query.py在第87执行获取连接时，传入了查询的db_name，在mongo.py第505行get_connection方法内，db_name赋值给了MongoClient方法的authSource参数，此参数为mongo账号的认证库名称，如果账号不是在db_name内创建就会提示认证失败，解决方法可参考图2，在获取连接时不传输db_name, 那么mongo get_connection方法就可以使用创建实例时的数据库名称 图1， ![image](https://user-images.githubusercontent.com/35388612/161244294-ae21499c-5aad-4964-9823-7841b19939e5.png) 图2, ![image](https://user-images.githubusercontent.com/35388612/161245486-c6242a1d-cd44-4ea7-bf6d-b72b995c0a7c.png)

最新的代码已经稍微有些变动，创建连接的逻辑进行了一些更改

**Comment by hhyo** [comment]
问题还存在吗？

**Comment by Myshiner** [comment]
最近没有弄这个，回头根据@weideguo的看看，如有问题再咨询

**Comment by Myshiner** [comment]
> > mongodb我也遇到了类似的问题，经查看代码发现query.py在第87执行获取连接时，传入了查询的db_name，在mongo.py第505行get_connection方法内，db_name赋值给了MongoClient方法的authSource参数，此参数为mongo账号的认证库名称，如果账号不是在db_name内创建就会提示认证失败，解决方法可参考图2，在获取连接时不传输db_name, 那么mongo get_connection方法就可以使用创建实例时的数据库名称 图1， ![image](https://user-images.githubusercontent.com/35388612/161244294-ae21499c-5aad-4964-9823-7841b19939e5.png) 图2, ![image](https://user-images.githubusercontent.com/35388612/161245486-c6242a1d-cd44-4ea7-bf6d-b72b995c0a7c.png)
> 
> 最新的代码已经稍微有些变动，创建连接的逻辑进行了一些更改

OK，您是已经更新了是吗，拉取新的代码就可以了？

**Comment by LT519** [comment]
我这边也遇到相同的问题了，麻烦问下你那边解决了没？怎么解决的？
archery版本：v1.8.2
mongo版本：4.2.14
mongo用户权限：
{
	"_id" : "admin.root",
	"userId" : UUID("e0ef3e02-eca2-43bc-9808-958ce3f44ae8"),
	"user" : "root",
	"db" : "admin",
	"roles" : [
		{
			"role" : "dbOwner",
			"db" : "quickai"
		},
		{
			"role" : "dbOwner",
			"db" : "xbot"
		},
		{
			"role" : "dbOwner",
			"db" : "quickai_test"
		},
		{
			"role" : "dbOwner",
			"db" : "quickai_gridfs"
		},
		{
			"role" : "dbAdmin",
			"db" : "xbot"
		},
		{
			"role" : "root",
			"db" : "admin"
		}
	],
	"mechanisms" : [
		"SCRAM-SHA-1",
		"SCRAM-SHA-256"
	]
}
上面说的方法都试过了，没有解决！！！
