### ISSUE TITLE
[ bug ]docker 部署执行 python3 manage.py makemigrations sql 出错

### ISSUE THREAD

**Issue by JulyXing** [hhyo/archer#1491]
### 重现步骤
```
docker exec -ti archery /bin/bash
cd /opt/archery
source /opt/venv4archery/bin/activate
python3 manage.py makemigrations sql  
```

### 期待结果和实际结果
期待结果：

实际结果:

### 错误日志

```
[root@91926bdc76df archery]# python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "/opt/archery/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python3/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/python3/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/python3/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python3/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/python3/lib/python3.9/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/archery/sql/models.py", line 5, in <module>
    from mirage import fields
ImportError: cannot import name 'fields' from 'mirage' (/usr/local/python3/lib/python3.9/site-packages/mirage/__init__.py)
```

### 版本信息
应用版本/分支：Release v1.8.4 

部署方式：Docker

**Comment by wang-xiaowu** [comment]
请问以下您是如何解决的

**Comment by 0vally1** [comment]
同问，我是手动部署，

**Comment by 0vally1** [comment]
pip install django-mirage-field
