### ISSUE TITLE
[ bug ] python3 manage.py makemigrations sql 执行的时候报错

### ISSUE THREAD

**Issue by 91dream** [hhyo/archer#1501]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

python3 manage.py makemigrations sql 执行的时候报错

### 期待结果和实际结果
期待结果：

实际结果:

### 错误日志

(venv4archery) [root@18382f7f03f5 archery]# python3 manage.py makemigrations sql
/opt/venv4archery/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "/opt/archery/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/urls/resolvers.py", line 593, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/urls/resolvers.py", line 586, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/archery/archery/urls.py", line 7, in <module>
    path('api/', include(('sql_api.urls', 'sql_api'), namespace="sql_api")),
  File "/opt/venv4archery/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/archery/sql_api/urls.py", line 7, in <module>
    from . import api_user, api_instance, api_workflow
  File "/opt/archery/sql_api/api_user.py", line 6, in <module>
    from .pagination import CustomizedPagination
  File "/opt/archery/sql_api/pagination.py", line 7, in <module>
    class CustomizedPagination(PageNumberPagination):
  File "/opt/archery/sql_api/pagination.py", line 11, in CustomizedPagination
    page_size = settings.REST_FRAMEWORK['PAGE_SIZE'] if 'PAGE_SIZE' in settings.REST_FRAMEWORK.keys() else 20
  File "/opt/venv4archery/lib/python3.9/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'REST_FRAMEWORK'
(venv4archery) [root@18382f7f03f5 archery]# 

### 版本信息
应用版本/分支：v1.8.4

部署方式：Docker、手工部署

部署方式：Docker部署。
docker镜像：hhyo/archery：v1.8.4

**Comment by nick2wang** [comment]
先手动修改一下settings.py
https://github.com/hhyo/Archery/issues/1489#issuecomment-1118129642

**Comment by 91dream** [comment]
sql初始化报错
(venv4archery) [root@61ca734522f4 archery]# python3 manage.py dbshell<sql/fixtures/auth_group.sql
Warning: Using a password on the command line interface can be insecure.
ERROR 1062 (23000) at line 2: Duplicate entry '1' for key 'PRIMARY'
CommandError: "mysql --user=root --password=123456 --host=mysql --port=3306 archery" returned non-zero exit status 1.

**Comment by nick2wang** [comment]
可能是你之前执行过这一步，python3 manage.py dbshell登录数据库把这几个表先清空：sql_instance_tag、auth_group、auth_group_permissions，然后再导入auth_group.sql

**Comment by 91dream** [comment]
已解决，感谢。
