### ISSUE TITLE
lock_cnt_threshold

### ISSUE THREAD

**Issue by 5sdba** [hhyo/archer#1524]
### 问题描述
update以后登录不了，从1.7.13升级到1.8.4

### 版本信息
 - 应用版本/分支：Release v1.8.4
 - 部署方式：Docker
 
已经升级过表结构，登录提示 

Internal Server Error: /authenticate/
--
2022-05-17 17:46:37 | Traceback (most recent call last):
2022-05-17 17:46:37 | File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
2022-05-17 17:46:37 | response = get_response(request)
2022-05-17 17:46:37 | File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
2022-05-17 17:46:37 | response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-05-17 17:46:37 | File "/opt/archery/common/auth.py", line 104, in authenticate_entry
2022-05-17 17:46:37 | result = new_auth.authenticate()
2022-05-17 17:46:37 | File "/opt/archery/common/auth.py", line 77, in authenticate
2022-05-17 17:46:37 | lock_count = int(self.sys_config.get('lock_cnt_threshold', 5))
2022-05-17 17:46:37 | ValueError: invalid literal for int() with base 10: 'C_2zzDLhBfoFnH9vDRwxvw=='

**Comment by nick2wang** [comment]
应该是升级时加密密钥变了，改回原来的密钥重启即可
https://github.com/hhyo/Archery/blob/f1d86773967201b451ab5a2cdc7d60dcabf72b40/archery/settings.py#L11

**Comment by 5sdba** [comment]
我看了下settings.py里面的是您发的这个

**Comment by 5sdba** [comment]
确实，感谢感谢
