### ISSUE TITLE
使用 LDAP 接入，第一次登录成功后下次登录就出现问题了

### ISSUE THREAD

**Issue by ethanliuu** [hhyo/archer#1533]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
使用 LDAP 接入，第一次登录成功后下次登录就出现问题了

### 配置文件
```python
      ENABLE_LDAP = True
      if ENABLE_LDAP:
          import ldap
          from django_auth_ldap.config import LDAPSearch
  
          AUTHENTICATION_BACKENDS = (
              'django_auth_ldap.backend.LDAPBackend',  # 配置为先使用LDAP认证，如通过认证则不再使用后面的认证方式
              'django.contrib.auth.backends.ModelBackend',  # django系统中手动创建的用户也可使用，优先级靠后。注意这2行的顺序
          )
          
          AUTH_LDAP_SERVER_URI = "ldap://xxx"
          AUTH_LDAP_BIND_DN = 'ou=users,o=xxx,dc=xx,dc=cn'
          AUTH_LDAP_BIND_PASSWORD = 'xxxxx'
          AUTH_LDAP_ALWAYS_UPDATE_USER = False
          AUTH_LDAP_USER_SEARCH = LDAPSearch(
              'ou=users,o=xx,dc=xxx,dc=cn',
              ldap.SCOPE_SUBTREE,
              '(&(email=%(user)s)(objectclass=posixAccount))',
          )
          AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
              "username": "cn",
              "display": "username",
              "email": "mail"
          }
```

### 错误日志
```
[2022-05-20 17:57:37,121][MainThread:140270579119936][task_id:django_auth_ldap][backend.py:374][WARNING]- (1062, "Duplicate entry 'liubin1' for key 'username'") while authenticating liubin1@xxx.xxx
[2022-05-20 17:57:37,126][MainThread:140270579119936][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/archery/common/auth.py", line 62, in authenticate
    user = Users.objects.get(username=username)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
sql.models.Users.DoesNotExist: Users matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'liubin1' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/common/auth.py", line 104, in authenticate_entry
    result = new_auth.authenticate()
  File "/opt/archery/common/auth.py", line 64, in authenticate
    authenticated_user = self.challenge(username=username, password=password)
  File "/opt/archery/common/auth.py", line 49, in challenge
    user = authenticate(username=username, password=password)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 153, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 211, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 355, in authenticate
    self._get_or_create_user()
  File "/opt/venv4archery/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 632, in _get_or_create_user
    self._user.save()
  File "/opt/archery/sql/models.py", line 52, in save
    super(Users, self).save(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'liubin1' for key 'username'")
```

### 期待结果和实际结果
期待结果：
正常登录
实际结果:
无法登录
### 截图
![image](https://user-images.githubusercontent.com/64894334/169506002-dd0ad9a6-e655-4855-abe9-bdb9edc09669.png)

### 版本信息
应用版本/分支：v 1.8.4

部署方式：Docker、手工部署

helm chart

**Comment by unknowissue** [comment]
"username": "cn",是不是中文呢？
换个唯一标识的非中文字段

**Comment by ethanliuu** [comment]
> "username": "cn",不是中文呢？ 换个唯一标识的中文字段呢？

不是中文是英文的

**Comment by unknowissue** [comment]
> 不是中文是英文的

我之前接入也有问题
后来用ldap的 sAMAccountName 这个字段搞定了
你可以试一试

**Comment by fancy-lee** [comment]
> > "username": "cn",不是中文呢？ 换个唯一标识的中文字段呢？
> 
> 不是中文是英文的

yum install openldap-clients
ldapsearch -x -H ldap://127.0.0.1:389 -b "dc=baidu,dc=com" -D "cn=admin,dc=baidu,dc=com" -w baidu  #注意：命令中的选项替换成你自己的配置
解决方法：执行上面的命令，查看一下有什么字段可以替换的，我用cn也不行同时也不是中文的，换了一个别的字段就没有问题了
