### ISSUE TITLE
mongoDB查询报错

### ISSUE THREAD

**Issue by xiaohei88** [hhyo/archer#1646]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

1、选择mongo实例
2、选择database
3、报错了

{$natural: -1} is not supported, full error: {'ok': 0.0, 'code': 303, 'errmsg': '{$natural: -1} is not supported', 'operationTime': Timestamp(1656479680, 1)}

</div>

### 预期外的结果

希望可以查询

### 日志文本

```shell
[2022-06-29 11:38:38,213][MainThread:140036986795840][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/instance.py", line 331, in describe
    if result['data']['error']:
TypeError: list indices must be integers or slices, not str

Internal Server Error: /instance/describetable/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/instance.py", line 331, in describe
    if result['data']['error']:
TypeError: list indices must be integers or slices, not str
```

### 版本

1.8.5

### 部署方式

K8S

**Comment by nick2wang** [comment]
duplicate of #1258
如果是Amazon DocumentDB的话可能不支持$natural排序，需要修改一下获取集合字段的逻辑

**Comment by xiaohei88** [comment]
我们用的amazon DocumentDB 4.0，看来只能改下下面的逻辑了
```java
    def get_all_columns_by_tb(self, db_name, tb_name, **kwargs):
        """获取所有字段, 返回一个ResultSet"""
        # https://github.com/getredash/redash/blob/master/redash/query_runner/mongodb.py
        result = ResultSet()
        db = self.get_connection()[db_name]
        collection_name = tb_name
        documents_sample = []
        if "viewOn" in db[collection_name].options():
            for d in db[collection_name].find().limit(2):
                documents_sample.append(d)
        else:
            for d in db[collection_name].find().sort([("$natural", 1)]).limit(1):
                documents_sample.append(d)

            for d in db[collection_name].find().sort([("$natural", -1)]).limit(1):
                documents_sample.append(d)
        columns = []
        # _merge_property_names
        for document in documents_sample:
            for prop in document:
                if prop not in columns:
                    columns.append(prop)
        result.column_list = ['COLUMN_NAME']
        result.rows = columns
        return result
```
