### ISSUE TITLE
v1.7.7升级到v1.8.5之后报“unknown column django_q_schedule.cron in 'field list'”错误

### ISSUE THREAD

**Issue by dengdalue** [hhyo/archer#1649]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

1.根据https://github.com/hhyo/archery/wiki/upgrade文档将archery从v1.7.7升级到v1.8.5
2.升级完之后能正常登录，但是在进行sql查询和sql上线时报“查询异常报错，错误信息:(1054,"unknown column django_q_schedule.cron in 'field list'")

### 预期外的结果

[2022-06-30 20:20:12,518][MainThread:140435016021824][task_id:default][query.py:170][ERROR]- 查询异常报错，查询语句：select * from crm_follow_up_record limit 100;
，错误信息：Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/sql/query.py", line 94, in query
    add_kill_conn_schedule(schedule_name, run_date, instance.id, thread_id)
  File "/opt/archery/sql/utils/tasks.py", line 21, in add_kill_conn_schedule
    del_schedule(name)
  File "/opt/archery/sql/utils/tasks.py", line 36, in del_schedule
    sql_schedule = Schedule.objects.get(name=name)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")

[2022-06-30 20:20:37,063][MainThread:139996487083840][task_id:django-q][cluster.py:663][ERROR]- (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")
[2022-06-30 20:21:07,177][MainThread:139996487083840][task_id:django-q][cluster.py:663][ERROR]- (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")

### 日志文本

```shell
[2022-06-30 20:20:12,518][MainThread:140435016021824][task_id:default][query.py:170][ERROR]- 查询异常报错，查询语句：select * from crm_follow_up_record limit 100;
，错误信息：Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/sql/query.py", line 94, in query
    add_kill_conn_schedule(schedule_name, run_date, instance.id, thread_id)
  File "/opt/archery/sql/utils/tasks.py", line 21, in add_kill_conn_schedule
    del_schedule(name)
  File "/opt/archery/sql/utils/tasks.py", line 36, in del_schedule
    sql_schedule = Schedule.objects.get(name=name)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")

[2022-06-30 20:20:37,063][MainThread:139996487083840][task_id:django-q][cluster.py:663][ERROR]- (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")
[2022-06-30 20:21:07,177][MainThread:139996487083840][task_id:django-q][cluster.py:663][ERROR]- (1054, "Unknown column 'django_q_schedule.cron' in 'field list'")
```

### 版本

1.8.5

### 部署方式

Docker

**Comment by LeoQuote** [comment]
可以试试 

python manage.py makemigration 
python manage.py migrate

**Comment by hhyo** [comment]
> 可以试试 
> 
> python manage.py makemigration 
> python manage.py migrate
> 

makemigration会把Archery自身的变更信息也生成，导致应用失败，项目提供变更sql就是因为不用自带的model管理，直接执行python manage.py migrate就行，主要是django自身和django_q用了migrate管理model

**Comment by hhyo** [comment]
版本跨越比较多的话，需要注意看下每个release的说明，有些有特殊说明

**Comment by dengdalue** [comment]
我新增cron字段之后就好了，问题已解决，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月30日(周四) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hhyo/Archery] v1.7.7升级到v1.8.5之后报“unknown column django_q_schedule.cron in 'field list'”错误 (Issue #1649)




 
版本跨越比较多的话，需要注意看下每个release的说明，有些有特殊说明

**Comment by weideguo** [comment]
根据实际经验，`v1.7.13`升级至`v1.8.5`存在django内部表字段缺失问题，因此除了运行`src/init_sql`下的文件之外，还需要运行
``` sql
alter table django_q_schedule add  `cron` varchar(100) DEFAULT NULL;
alter table django_q_task add `attempt_count` int(11) NOT NULL;
```

**Comment by Yebolin** [comment]
是不是应该增加或者更新一下 init_sql
我也遇到一样的问题

**Comment by feiazifeiazi** [comment]
需要加这个字段。
ALTER TABLE django_q_schedule ADD cluster varchar(100) DEFAULT NULL;


https://blog.csdn.net/qq_42273045/article/details/130986980
