### ISSUE TITLE
archery 查询sharding-proxy数据库源时候会报错

### ISSUE THREAD

**Issue by skymoou** [hhyo/archer#1665]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

1、创建 sharding-proxy 的数据源
2、使用 sharding 数据源进行查询

### 预期外的结果

10002, '2Unknown exception: [Unsupported SQL of `explain select 1`]'

### 日志文本

```shell
[2022-07-08 17:34:37,227][MainThread:140502183216960][task_id:default][mysql.py:270][WARNING]- MySQL语句执行报错，语句：explain select 1，错误信息Traceback (most recent call last):
  File "/opt/archery/Archery/sql/engines/mysql.py", line 259, in query
    effect_row = cursor.execute(sql)
  File "/usr/local/python3/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/python3/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/python3/lib/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (10002, '2Unknown exception: [Unsupported SQL of `explain select 1`]')
```

### 版本

1.8.5

### 部署方式

手工部署

**Comment by skymoou** [comment]
1
