### ISSUE TITLE
AttributeError: module 'MySQLdb' has no attribute 'escape_string'

### ISSUE THREAD

**Issue by 0vally1** [hhyo/archer#1682]
### 重现步骤

点击SQL分析，选择实例，直接报错
AttributeError: module 'MySQLdb' has no attribute 'escape_string'

### 预期外的结果

[2022-07-15 11:45:45,432][Thread-74 (process_request_thread):13768][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "D:\pythonwork\Archery\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\pythonwork\Archery\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\pythonwork\Archery\sql\db_diagnostic.py", line 39, in process
    query_result = query_engine.processlist(command_type)
  File "D:\pythonwork\Archery\sql\engines\mysql.py", line 449, in processlist
    command_type = MySQLdb.escape_string(command_type).decode('utf-8')
AttributeError: module 'MySQLdb' has no attribute 'escape_string'
Internal Server Error: /db_diagnostic/process/
Traceback (most recent call last):
  File "D:\pythonwork\Archery\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\pythonwork\Archery\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\pythonwork\Archery\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\pythonwork\Archery\sql\db_diagnostic.py", line 39, in process
    query_result = query_engine.processlist(command_type)
  File "D:\pythonwork\Archery\sql\engines\mysql.py", line 449, in processlist
    command_type = MySQLdb.escape_string(command_type).decode('utf-8')
AttributeError: module 'MySQLdb' has no attribute 'escape_string'
[15/Jul/2022 11:45:45] "POST /db_diagnostic/process/ HTTP/1.1" 500 14289

### 日志文本

```shell
开发工具启动的
```

### 版本

最新master分支代码

### 部署方式

手工部署

**Comment by hhyo** [comment]
- 不要参考其他方式使用pymysql替代，需要正常安装mysqlclient
- 请使用依赖文件中的版本，不要随意升级

**Comment by 0vally1** [comment]
> * 参考别用其他方式使用pymysql，需要正常安装mysqlclient
> * 请使用文件中的版本，不要随意升级依赖

我在Linux上不使用docker的情况下是正常安装无报错可以使用的，但是在Windows上会遇见这个问题，大佬，你是用windows的Pycharm工具开发吗，加个联系方式呗，0vally1010@gmail.com，联系方式发送到这个邮箱

**Comment by LeoQuote** [comment]
开发还是要多探索探索哈
