### ISSUE TITLE
python3.9 依赖MySQLdb问题

### ISSUE THREAD

**Issue by majingpu** [hhyo/archer#1716]
### 重现步骤

1.安装Python3.9解释器
2.下载最新版archery
3.`pip install -r requirements.txt`
4. 启动server 

报错:
```
NameError: name '_mysql' is not defined
```

### 预期外的结果

使用最新版archery在本地调试，启动server报错
```
import local settings failed, ignored
import local settings failed, ignored
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/MySQLdb/_mysql.cpython-39-darwin.so, 2): Symbol not found: _mysql_affected_rows
  Referenced from: /Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/MySQLdb/_mysql.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/MySQLdb/_mysql.cpython-39-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/db/models/base.py", line 141, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/db/models/base.py", line 369, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/db/models/options.py", line 235, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/db/utils.py", line 208, in create_connection
    backend = load_backend(db["ENGINE"])
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/Users/leyan-noc/Desktop/pythonProject/Archery/venv/lib/python3.9/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

Google的结果是python3.5之后不支持MySQLdb使用，而是使用pymysql。

在`archery/__init__.py`文件增加以下代码解决该问题
```
import pymysql
pymysql.version_info = (2, 0, 3, "final", 0)
pymysql.install_as_MySQLdb()
```

同时会遇到一个新问题，点击页面`sql审核->sql上线`,选择实例的时候会报错
```
'str' object has no attribute 'decode'
```
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/49381462/181669345-c5a11007-4280-401f-aa8f-83ac1bb9563f.png">

### 版本

1.8.5

### 部署方式

手工部署

**Comment by hhyo** [comment]
可以在网上检索下mysqlclient 的安装方法，相关错误搜索下有很多解决方案https://github.com/PyMySQL/mysqlclient
