### ISSUE TITLE
执行`python3 manage.py makemigrations sql`后报错

### ISSUE THREAD

**Issue by wang-xiaowu** [hhyo/archer#1757]
### 重现步骤

0.clone
git clone && cd Archery/src/docker-compose
1.启动
docker-compose up -d

2.表结构初始化
docker exec -ti archery /bin/bash
cd /opt/archery
source /opt/venv4archery/bin/activate
python3 manage.py makemigrations sql

### 预期外的结果

在执行`python3 manage.py makemigrations sql`后报错
```
[root@f9785a833972 archery]# source /opt/venv4archery/bin/activate
(venv4archery) [root@f9785a833972 archery]# python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/migrations/loader.py", line 290, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")
```

### 版本

1.8.5

### 部署方式

Docker

**Comment by wang-xiaowu** [comment]
可以了, 我得自己改`archery/settings.py`文件下的配置...
docker-compose下的参数没生效

**Comment by wang-xiaowu** [comment]
> 我得自己改`archery/settings.py`文件下的配置...

麻烦

**Comment by wang-xiaowu** [comment]
> 我得自己改`archery/settings.py`文件下的配置...

麻烦作者看下这里的问题把

**Comment by dengpei89** [comment]
> 可以了, 我得自己改`archery/settings.py`文件下的配置... docker-compose下的参数没生效

除了这个，还有个问题，由于docker-compose.yml里mysql映射了已存在的数据库目录，导致设置的MYSQL_ROOT_PASSWORD变量没有生效。
![图片](https://user-images.githubusercontent.com/26969979/184840596-7789c846-877e-4d82-a46c-2b1cd03584b5.png)
因为我是测试，可以注释掉这一行，
如果是生产环境，让宿主机的datadir目录为空即可

**Comment by 0ck0** [comment]
> 可以了, 我得自己改`archery/settings.py`文件下的配置... docker-compose下的参数没生效

相同的问题，请问`archery/settings.py` 修改了啥内容？
