### ISSUE TITLE
helm 安装后  archery应用一直会连127.0.0.1:3306

### ISSUE THREAD

**Issue by smallhorsegg** [hhyo/archer#1777]
### 重现步骤

helm 安装后  archery应用一直会连127.0.0.1:3306

### 预期外的结果

mysql:
  embedded: true
  url: "mysql://root:@archery-mysql:3306/archery"
  urlSecret: ""
  urlSecretKey: "DATABASE_URL"
  # embedded 为 false时, 会使用外部的 mysql, 下方的 mysql 配置不会生效
  architecture: standalone
  auth:
    database: archery
    rootPassword: ""
  primary:
    configuration: |-

### 日志文本

```shell
[2022-08-16 17:06:31,913][MainThread:140483195447104][task_id:default][config.py:33][ERROR]- 获取系统配置信息失败:(2003, "Can't connect to MySQL server on '127.0.0.1' (111)")Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
```

### 版本

1.8.5

### 部署方式

K8S

**Comment by LeoQuote** [comment]
你好, 推荐你使用这个 helm repo https://github.com/douban/charts/tree/master/charts/archery 有什么不明白的可以在这里回复, 问题我集中再更新到 chart 里
