### ISSUE TITLE
用 docker 新部署的 archery v1.8.5 ，添加负载均衡无法使用

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/archer#1786]
### 重现步骤

1. 用docker方式部署v1.8.5版本的archery（默认配置，未修改任何内容）
2. 用 ip 连接的方式打开 archery 的首页（http://ip:9123），正常
![image](https://user-images.githubusercontent.com/40595864/185534447-a959b372-339a-452d-8f2b-c7b375657b7c.png)

4. 使用腾讯云的负载均衡（负载均衡参数默认），添加域名指向 archery 服务器的 9123 端口，以及添加 DNS 解析后，用域名的方式打开 archery 首页，报错：Internal Server Error
![image](https://user-images.githubusercontent.com/40595864/185534362-c7d5ae9b-5767-4568-bedc-0688522e1e4c.png)

5. 用 `docker logs archery -f --tail=10` 查看日志，报错：
```
[2022-08-19 11:03:10 +0800] [29] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/http/request.py", line 137, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'archerxxx.xxxang.com:9123'. The domain name provided is not valid according to RFC 1034/1035.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 121, in get_exception_response
    response = callback(request, **{**param_dict, 'exception': exception})
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/archery/common/views.py", line 21, in bad_request
    return HttpResponseBadRequest(render(request, template_name))
  File "/opt/venv4archery/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/usr/local/python3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/opt/archery/common/utils/global_info.py", line 8, in global_info
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'
```

### 预期外的结果

![image](https://user-images.githubusercontent.com/40595864/185533911-afeac8da-35e9-4cd1-ac86-b6979db5b3c5.png)
![image](https://user-images.githubusercontent.com/40595864/185535151-654cfe77-671a-4398-8b7b-7d1d88119b96.png)

### 日志文本

```shell
1. logs/archery.log日志为空，logs/qcluster.log不存在

root@vpn-test:/opt/Archery-1.8.5/src/docker-compose# ll archery/logs/
total 12
drwxr-xr-x 2 root root 4096 Aug 19 10:58 ./
drwxrwxr-x 6 root root 4096 Aug 19 10:56 ../
-rw-r--r-- 1 root root    0 Aug 19 10:58 archery.log
-rw-r--r-- 1 root root 1434 Aug 19 10:58 supervisord.log
```
3. docker logs archery -f --tail=10
```
[2022-08-19 11:03:10 +0800] [29] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/http/request.py", line 137, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'archexxx.xxxang.com:9123'. The domain name provided is not valid according to RFC 1034/1035.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 121, in get_exception_response
    response = callback(request, **{**param_dict, 'exception': exception})
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/archery/common/views.py", line 21, in bad_request
    return HttpResponseBadRequest(render(request, template_name))
  File "/opt/venv4archery/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/usr/local/python3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/opt/archery/common/utils/global_info.py", line 8, in global_info
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'

```
```


### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

无

**Comment by huliangshan** [comment]
我使用k8s部署的，也有这个问题，我没走负载均衡也不能访问，

**Comment by huliangshan** [comment]
我使用k8s部署的，也有这个问题，我没走负载均衡也不能访问，我的解决方案是：

**Comment by huliangshan** [comment]
我使用k8s部署的，也有这个问题，我没走负载均衡也不能访问。我的解决方案

**Comment by huliangshan** [comment]
我使用k8s部署的，也有这个问题，我没走负载均衡也不能访问，我的解决方式是修改nginx配置文件注释 该行 proxy_set_header X-Forwarded-Host  $host:nginx_port;

**Comment by LeoQuote** [comment]
日志都很清楚，不在trusted host里面，你们稍微搜一下就有方案了

**Comment by michael-liumh** [comment]
> 日志都很清楚，不在trusted host里面，你们稍微搜一下就有方案了

我这使用的是默认配置`ALLOWED_HOSTS = ['*']`，这个是属于没做限制的

**Comment by nick2wang** [comment]
看报错是域名不符合规范，django的domain不支持下划线"_"，可以尝试下修改域名
https://github.com/django/django/blob/0b8a0296bfd30748f08021834e95cdae241686e8/django/http/request.py#L28

**Comment by michael-liumh** [comment]
> 看报错是域名不符合规范，django的domain不支持下划线"_"，可以尝试下修改域名 https://github.com/django/django/blob/0b8a0296bfd30748f08021834e95cdae241686e8/django/http/request.py#L28

谢谢，确实是这个原因

**Comment by michael-liumh** [comment]
已添加到部署文档的FAQ里

https://github.com/hhyo/Archery/wiki#%E6%B7%BB%E5%8A%A0%E5%89%8D%E7%AB%AF%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%E5%90%8E%E7%94%A8%E5%9F%9F%E5%90%8D%E8%AE%BF%E9%97%AE%E6%8A%A5%E9%94%99

**Comment by LeoQuote** [comment]
你加到页脚里去了

**Comment by LeoQuote** [comment]
FAQ 中请不要这样贴出长篇的错误, 请捡出重点的报错, 比如这里的是 `django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'archexxx.xxxang.com:9123'. The domain name provided is not valid according to RFC 1034/1035.`

**Comment by michael-liumh** [comment]
> 你加到页脚里去了

已修正
