### ISSUE TITLE
升级到1.8.4以后无法登陆

### ISSUE THREAD

**Issue by OpenSourceApp-coder** [hhyo/archer#1798]
### 重现步骤

原始版本是1.8.1 现在由于修复limit 查询bug 及支持goinception的脱敏。目标升级到1.8.4；
正常升级，升级了python依赖，目前python环境是python3.6；
升级完成后无法登陆，报错信息如下：
Internal Server Error: /authenticate/
Traceback (most recent call last):
  File "/app/venv4archery/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/venv4archery/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/Archery-1.8.4/common/auth.py", line 105, in authenticate_entry
    result = new_auth.authenticate()
  File "/app/Archery-1.8.4/common/auth.py", line 77, in authenticate
    lock_count = int(self.sys_config.get('lock_cnt_threshold', 5))
ValueError: invalid literal for int() with base 10: 'mscJdEaCwlO5uuIXMGiu_Q=='

经排查:Archery/common/config.py  文件获取的sysconfig未解密，导致验证时出现问题；同服务器1.8.1版本无问题；

### 预期外的结果

经排查：之前1.8.1环境之所以正常是由于取到的sysconfig的value值都为空，导致使用了默认值；

现升级到1.8.4后，sysconfig从sql_config中取到的值都是原值没有解密

排查到的地方：
def get_all_config(self):
        try:
            # 获取系统配置信息
            all_config = Config.objects.all().values('item', 'value')
            logger.error('----------555555555555555555all_config -' + str(all_config))
            sys_config = {}
            for items in all_config:
                if items['value'] in ('true', 'True'):
                    items['value'] = True
                elif items['value'] in ('false', 'False'):
                    items['value'] = False
                sys_config[items['item']] = items['value']
            self.sys_config = sys_config
            logger.error('----------666666666666666666666666sys_config -' + str(sys_config))
        except Exception as m:
            logger.error(f"获取系统配置信息失败:{m}{traceback.format_exc()}")
            self.sys_config = {}

### 日志文本

```shell
1.8.1的对应日志
555555555555555555all_config -<QuerySet
 [{'item': 'admin_query_limit', 'value': ''}, {'item': 'archery_base_url', 'value': ''}, {'item': 'auto_review', 'value': ''}, {'item': 'auto_review_max_update_rows', 'value': ''}, {'item': 'auto_review_regex', 'value': ''}, {'item': 'auto_review_tag', 'value': ''}, {'item': 'auto_review_wrong', 'value': ''}, {'item': 'binlog2sql', 'value': '/root/DBAScripts/binlog2sql/binlog2sql/binlog2sql.py'}, {'item': 'critical_ddl_regex', 'value': ''}, {'item': 'data_masking', 'value': ''}, {'item': 'ddl_notify_auth_group', 'value': ''}, {'item': 'default_auth_group', 'value': ''}, {'item': 'default_resource_group', 'value': ''}, {'item': 'ding', 'value': ''}, {'item': 'ding_agent_id', 'value': ''}, {'item': 'ding_app_key', 'value': ''}, {'item': 'ding_app_secret', 'value': ''}, {'item': 'ding_archery_username', 'value': ''}, {'item': 'ding_dept_ids', 'value': ''}, {'item': 'ding_to_person', 'value': ''}, '...(remaining elements truncated)...']>
[2022-08-23 15:27:27,252][Thread-5:139787070277376][task_id:default][config.py:33][ERROR]- ----------666666666666666666666666sys_config -
{'admin_query_limit': '', 'archery_base_url': '', 'auto_review': '', 'auto_review_max_update_rows': '', 'auto_review_regex': '', 'auto_review_tag': '', 'auto_review_wrong': '', 'binlog2sql': '/root/DBAScripts/binlog2sql/binlog2sql/binlog2sql.py', 'critical_ddl_regex': '', 'data_masking': '', 'ddl_notify_auth_group': '', 'default_auth_group': '', 'default_resource_group': '', 'ding': '', 'ding_agent_id': '', 'ding_app_key': '', 'ding_app_secret': '', 'ding_archery_username': '', 'ding_dept_ids': '', 'ding_to_person': '', 'disable_star': '', 'enable_backup_switch': False, 'feishu': '', 'feishu_appid': '', 'feishu_app_secret': '', 'feishu_webhook': '', 'go_inception_host': '10.206.113.2', 'go_inception_port': '4000', 'inception_host': '', 'inception_port': '', 'inception_remote_backup_host': '10.206.97.159', 'inception_remote_backup_password': 'F_5aGr1li.(c83RX', 'inception_remote_backup_port': '3397', 'inception_remote_backup_user': 'cosmords', 'index_path_url': '', 'lock_cnt_threshold': '', 'lock_time_threshold': '', 'mail': '', 'mail_smtp_password': '', 'mail_smtp_port': '', 'mail_smtp_server': '', 'mail_smtp_user': '', 'mail_ssl': '', 'manual': '', 'max_execution_time': '', 'query_check': '', 'qywx_webhook': '', 'sign_up_enabled': '', 'soar': '/root/DBAScripts/soar/soar.linux-amd64', 'soar_test_dsn': 'soar:CoBIU^^__123Xob@10.206.97.159:3397/test_soar', 'sqladvisor': '', 'wx': '', 'wx_agent_id': '', 'wx_app_secret': '', 'wx_corpid': ''}


1.8.4的对应日志
----------555555555555555555all_config -<QuerySet [{'item': 'admin_query_limit', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'archery_base_url', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'auto_review', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'auto_review_max_update_rows', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'auto_review_regex', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'auto_review_tag', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'auto_review_wrong', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'binlog2sql', 'value': 'Ws3TFXf9fx9aeHlr9ALzWmRzE6wGSB0Ppl2kJN5bNx6iJE1PC9WZHUnhCbAYU9ikNVeA5XnpeqgQ7UHRfP3Q5A=='}, {'item': 'critical_ddl_regex', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'data_masking', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ddl_notify_auth_group', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'default_auth_group', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'default_resource_group', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding_agent_id', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding_app_key', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding_app_secret', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding_archery_username', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding_dept_ids', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, {'item': 'ding_to_person', 'value': 'mscJdEaCwlO5uuIXMGiu_Q=='}, '...(remaining elements truncated)...']>
[2022-08-23 15:33:28,836][Thread-11:139771913631488][task_id:default][config.py:33][ERROR]- ----------666666666666666666666666sys_config -{'admin_query_limit': 'mscJdEaCwlO5uuIXMGiu_Q==', 'archery_base_url': 'mscJdEaCwlO5uuIXMGiu_Q==', 'auto_review': 'mscJdEaCwlO5uuIXMGiu_Q==', 'auto_review_max_update_rows': 'mscJdEaCwlO5uuIXMGiu_Q==', 'auto_review_regex': 'mscJdEaCwlO5uuIXMGiu_Q==', 'auto_review_tag': 'mscJdEaCwlO5uuIXMGiu_Q==', 'auto_review_wrong': 'mscJdEaCwlO5uuIXMGiu_Q==', 'binlog2sql': 'Ws3TFXf9fx9aeHlr9ALzWmRzE6wGSB0Ppl2kJN5bNx6iJE1PC9WZHUnhCbAYU9ikNVeA5XnpeqgQ7UHRfP3Q5A==', 'critical_ddl_regex': 'mscJdEaCwlO5uuIXMGiu_Q==', 'data_masking': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ddl_notify_auth_group': 'mscJdEaCwlO5uuIXMGiu_Q==', 'default_auth_group': 'mscJdEaCwlO5uuIXMGiu_Q==', 'default_resource_group': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding_agent_id': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding_app_key': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding_app_secret': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding_archery_username': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding_dept_ids': 'mscJdEaCwlO5uuIXMGiu_Q==', 'ding_to_person': 'mscJdEaCwlO5uuIXMGiu_Q==', 'disable_star': 'mscJdEaCwlO5uuIXMGiu_Q==', 'enable_backup_switch': 'hgV-NmnHrWStS76C9kTw_A==', 'feishu': 'mscJdEaCwlO5uuIXMGiu_Q==', 'feishu_appid': 'mscJdEaCwlO5uuIXMGiu_Q==', 'feishu_app_secret': 'mscJdEaCwlO5uuIXMGiu_Q==', 'feishu_webhook': 'mscJdEaCwlO5uuIXMGiu_Q==', 'go_inception_host': 'bekyv5CZon0nlau7HiEhvw==', 'go_inception_port': 'lRS_zfu2KG-BIWCbl20FxA==', 'inception_host': 'mscJdEaCwlO5uuIXMGiu_Q==', 'inception_port': 'mscJdEaCwlO5uuIXMGiu_Q==', 'inception_remote_backup_host': 'dNDlrpyXg4kIjNxUNAvaXA==', 'inception_remote_backup_password': 'oOC4vOiMIrY4yeDSiWSRMprHCXRGgsJTubriFzBorv0=', 'inception_remote_backup_port': 'AZAo00syv6e1xd18KxEPCg==', 'inception_remote_backup_user': 'IkMmMzA0qg0gamkzjpKUuA==', 'index_path_url': 'mscJdEaCwlO5uuIXMGiu_Q==', 'lock_cnt_threshold': 'mscJdEaCwlO5uuIXMGiu_Q==', 'lock_time_threshold': 'mscJdEaCwlO5uuIXMGiu_Q==', 'mail': 'mscJdEaCwlO5uuIXMGiu_Q==', 'mail_smtp_password': 'mscJdEaCwlO5uuIXMGiu_Q==', 'mail_smtp_port': 'mscJdEaCwlO5uuIXMGiu_Q==', 'mail_smtp_server': 'mscJdEaCwlO5uuIXMGiu_Q==', 'mail_smtp_user': 'mscJdEaCwlO5uuIXMGiu_Q==', 'mail_ssl': 'mscJdEaCwlO5uuIXMGiu_Q==', 'manual': 'mscJdEaCwlO5uuIXMGiu_Q==', 'max_execution_time': 'mscJdEaCwlO5uuIXMGiu_Q==', 'query_check': 'mscJdEaCwlO5uuIXMGiu_Q==', 'qywx_webhook': 'mscJdEaCwlO5uuIXMGiu_Q==', 'sign_up_enabled': 'mscJdEaCwlO5uuIXMGiu_Q==', 'soar': 'Ws3TFXf9fx9aeHlr9ALzWkeRNXHQJH3XGj6KqgexJF5KQE3sXTmufi2euQ1L-IkA', 'soar_test_dsn': '_WvzyxOjleCIsYkDYI4SfHLPhVZA--44Bw9PoBENS0Ukheocd6Sfk-BeMO9F9r1xsweAPF6XFAkGmK6ET8gwAA==', 'sqladvisor': 'mscJdEaCwlO5uuIXMGiu_Q==', 'wx': 'mscJdEaCwlO5uuIXMGiu_Q==', 'wx_agent_id': 'mscJdEaCwlO5uuIXMGiu_Q==', 'wx_app_secret': 'mscJdEaCwlO5uuIXMGiu_Q==', 'wx_corpid': 'mscJdEaCwlO5uuIXMGiu_Q=='}
```

### 版本

1.8.4

### 部署方式

手工部署

**Comment by nick2wang** [comment]
排查下是否密钥问题 #1524

**Comment by OpenSourceApp-coder** [comment]
非常感谢已解决
