### ISSUE TITLE
helm安装的archery，配置使用外部的mysql但是接连一直是(2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

### ISSUE THREAD

**Issue by imyuanandyou** [hhyo/archer#1851]
### 重现步骤

1、使用https://github.com/hhyo/Archery/tree/master/src/charts提供的chat（考虑放到helm仓库吗，后面好升级）
2、更改values.yaml文件（这里的url和urlSecret应该是二选其一吧，总之都试了还是连接到127.0.0.1）
mysql:
  embedded: false
  url: "mysql://archery:xxxx@mysql:3306/archery"
  #urlSecret: "mysql://archery:xxxx@mysql:3306/archery"
  #urlSecretKey: "DATABASE_URL"
  # embedded 为 false时, 会使用外部的 mysql, 下方的 mysql 配置不会生效
  architecture: standalone

3、install后在pod内能看到系统env的环境变量为 （不理解py程序是怎么通过获取到DATABASE_URL的值的，全局搜了关键字也没找到对DATABASE_URL的引用）
DATABASE_URL="mysql://archery:xxxx@mysql:3306/archery"

之前有个类似的issue不过没给出答案已经关掉了
https://github.com/hhyo/Archery/issues/1777

### 预期外的结果

无论是初始化容器还是archery容器的日志连接都是报错django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

### 日志文本

```shell
初始化容器的：：
 切换python运行环境

 Traceback (most recent call last):

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

     self.connection = self.get_new_connection(conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

     return Database.connect(**conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect

     return Connection(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__

     super().__init__(*args, **kwargs2)

 MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

 

 The above exception was the direct cause of the following exception:

 

 Traceback (most recent call last):

   File "/opt/archery/manage.py", line 10, in <module>

     execute_from_command_line(sys.argv)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

     utility.execute()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute

     self.fetch_command(subcommand).run_from_argv(self.argv)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv

     self.execute(*args, **cmd_options)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute

     output = self.handle(*args, **options)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped

     res = handle_func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle

     loader.check_consistent_history(connection)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/migrations/loader.py", line 290, in check_consistent_history

     applied = recorder.applied_migrations()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations

     if self.has_table():

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table

     with self.connection.cursor() as cursor:

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor

     return self._cursor()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor

     self.ensure_connection()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__

     raise dj_exc_value.with_traceback(traceback) from exc_value

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

     self.connection = self.get_new_connection(conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

     return Database.connect(**conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect

     return Connection(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__

     super().__init__(*args, **kwargs2)

 django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

 Traceback (most recent call last):

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

     self.connection = self.get_new_connection(conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

     return Database.connect(**conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect

     return Connection(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__

     super().__init__(*args, **kwargs2)

 MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

 

 The above exception was the direct cause of the following exception:

 

 Traceback (most recent call last):

   File "/opt/archery/manage.py", line 10, in <module>

     execute_from_command_line(sys.argv)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

     utility.execute()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute

     self.fetch_command(subcommand).run_from_argv(self.argv)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv

     self.execute(*args, **cmd_options)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute

     output = self.handle(*args, **options)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped

     res = handle_func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle

     self.check(databases=[database])

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check

     all_issues = checks.run_checks(

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/registry.py", line 70, in run_checks

     new_errors = check(app_configs=app_configs, databases=databases)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/database.py", line 13, in check_database_backends

     issues.extend(conn.validation.check(**kwargs))

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/validation.py", line 9, in check

     issues.extend(self._check_sql_mode(**kwargs))

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode

     if not (self.connection.sql_mode & {'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES'}):

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__

     res = instance.__dict__[self.name] = self.func(instance)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 376, in sql_mode

     with self.cursor() as cursor:

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor

     return self._cursor()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor

     self.ensure_connection()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__

     raise dj_exc_value.with_traceback(traceback) from exc_value

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

     self.connection = self.get_new_connection(conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

     return Database.connect(**conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect

     return Connection(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__

     super().__init__(*args, **kwargs2)

 django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

 ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

 CommandError: "mysql --user=root --host=127.0.0.1 --port=3306 archery" returned non-zero exit status 1.

 ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

 CommandError: "mysql --user=root --host=127.0.0.1 --port=3306 archery" returned non-zero exit status 1.

 Error,用户重复创建或创建失败，请登录pod检查!




----------------
archery容器的
 [2022-09-22 11:47:53,294][MainThread:140308668098368][task_id:default][config.py:33][ERROR]- 获取系统配置信息失败:(2003, "Can't connect to MySQL server on '127.0.0.1' (111)")Traceback (most recent call last):

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

     self.connection = self.get_new_connection(conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

     return Database.connect(**conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect

     return Connection(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__

     super().__init__(*args, **kwargs2)

 MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")
```

### 版本

1.8.5

### 部署方式

K8S

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql版本8已经手动创建库和账号，并能保证连上

**Comment by LeoQuote** [comment]
我推荐你使用这里的 helm chart -> https://github.com/douban/charts/tree/master/charts/archery

**Comment by imyuanandyou** [comment]
换了豆瓣的chart还是不行同样报错
pod内
env | grep DATA
DATABASE_URL=mysql://archery:xxxxx@mysql:3306/archery

----
 [2022-09-22 13:43:14,893][MainThread:139998040823616][task_id:default][config.py:33][ERROR]- 获取系统配置信息失败:(2003, "Can't connect to MySQL server on '127.0.0.1' (111)")Traceback (most recent call last):

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

     self.connect()

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

     self.connection = self.get_new_connection(conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

     return func(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

     return Database.connect(**conn_params)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect

     return Connection(*args, **kwargs)

   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__

     super().__init__(*args, **kwargs2)

 MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

 

 The above exception was the direct cause of the following exception:


----
系统变量DATABASE_URL是从哪里注入到程序内的

**Comment by imyuanandyou** [comment]
找到了配置文件/opt/archery/archery/settings.py内找到了DB的
DATABASES配置127.0.0.1
同时文档描述
"LDAP设置 如需启用LDAP，修改value.yaml里comfigmap下settings.py 内相关内容。"
-----
可我看了value.yaml没有settings.py的configmap，只有local_settings.py的
local_settings.py添加了以下配置还是报错链接到127.0.0.1
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'archery',
                'USER': 'archery',
                'PASSWORD': 'xxx,
                'HOST': 'mysql-xxx,
                'PORT': '3306',
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4'
                },
                'TEST': {
                    'NAME': 'test_archery',
                    'CHARSET': 'utf8mb4',
                },
            }
        }

**Comment by LeoQuote** [comment]
你这个问题应该是因为你没有使用最新版的archery镜像导致的，你可以手动修改镜像版本到最新，master或者1.9.0 都可

**Comment by imyuanandyou** [comment]
手动更换镜像到1.9.0解决了
