### ISSUE TITLE
[BUG]docker安装报错

### ISSUE THREAD

**Issue by cp7719** [hhyo/archer#1876]
### 重现步骤

unbantu18.04环境下使用docker安装报异常
执行python3 manage.py makemigrations sql语句，mysql和redis都在docker内

### 预期外的结果

python3 manage.py makemigrations sql  执行失败

### 日志文本

```shell
异常如下：
/opt/venv4archery/lib/python3.9/site-packages/environ/environ.py:548: UserWarning: Engine not recognized from url: {'NAME': 'mysql://root:123456@mysql:3306/archery"', 'USER': '', 'PASSWORD': '', 'HOST': '', 'PORT': '', 'ENGINE': ''}
  warnings.warn("Engine not recognized from url: {}".format(config))
Traceback (most recent call last):
  File "/opt/archery/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/checks/translation.py", line 53, in check_setting_languages_bidi
    for tag in settings.LANGUAGES_BIDI
  File "/opt/venv4archery/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/archery/archery/settings.py", line 185, in <module>
    "default": env.cache(),
  File "/opt/venv4archery/lib/python3.9/site-packages/environ/environ.py", line 293, in cache_url
    return self.cache_url_config(
  File "/opt/venv4archery/lib/python3.9/site-packages/environ/environ.py", line 568, in cache_url_config
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Invalid cache schema
```

### 版本

1.9.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql5.7

**Comment by 402309718** [comment]
centos7.6也是一样报错

**Comment by 402309718** [comment]
修改src/docker-compose/.env  文件把里面URL的"全部去除就可以启动了

**Comment by jimsoft1000** [comment]
我也遇到过，没仔细研究，把mysql容器去掉，使用自己搭建的MySQL数据库，就不会有问题

**Comment by peng19832** [comment]
> 修改src/docker-compose/.env 文件把里面URL的"全部去除就可以启动了

那个url里不能有特殊字符，实施换成字符的十六进制格式试试呢
