### ISSUE TITLE
查看top表空间报错。

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/archer#1949]
### 重现步骤

有的实例选择top表空间页面时候，会比较慢， 然后报错。

### 预期外的结果

![image](https://user-images.githubusercontent.com/59639792/199670041-dfe56c4f-6760-4632-93cf-88d9b4718c2a.png)

### 日志文本

```shell
[2022-11-03 15:49:29,051][MainThread:139760437573440][task_id:default][mysql.py:269][WARNING]- MySQL语句执行报错，语句：
        SELECT
          table_schema AS table_schema,
          table_name AS table_name,
          engine AS engine,
          TRUNCATE((data_length+index_length+data_free)/1024/1024,2) AS total_size,
          table_rows AS table_rows,
          TRUNCATE(data_length/1024/1024,2) AS data_size,
          TRUNCATE(index_length/1024/1024,2) AS index_size,
          TRUNCATE(data_free/1024/1024,2) AS data_free,
          TRUNCATE(data_free/(data_length+index_length+data_free)*100,2) AS pct_free
        FROM information_schema.tables
        WHERE table_schema NOT IN ('information_schema', 'performance_schema', 'mysql', 'test', 'sys')
          ORDER BY total_size DESC
        LIMIT 14;，错误信息Traceback (most recent call last):
  File "/app/archery/archery1.8.5/sql/engines/mysql.py", line 258, in query
    effect_row = cursor.execute(sql)
  File "/app/archery/Python-3.9.1/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/app/archery/Python-3.9.1/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/app/archery/Python-3.9.1/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/app/archery/Python-3.9.1/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (1690, "BIGINT UNSIGNED value is out of range in '((`information_schema`.`tables`.`DATA_LENGTH` + `information_schema`.`tables`.`INDEX_LENGTH`) + `information_schema`.`tables`.`DATA_FREE`)'")
```

### 版本

1.8.5

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL 5.7.37

**Comment by gaoqiang-0327** [comment]
"""获取表空间信息"""
        sql = """
        SELECT
          table_schema AS table_schema,
          table_name AS table_name,
          engine AS engine,
          TRUNCATE((data_length+index_length+data_free)/1024/1024,2) AS total_size,
          table_rows AS table_rows,
          TRUNCATE(data_length/1024/1024,2) AS data_size,
          TRUNCATE(index_length/1024/1024,2) AS index_size,
          TRUNCATE(data_free/1024/1024,2) AS data_free,
          TRUNCATE(data_free/(data_length+index_length+data_free)*100,2) AS pct_free
        FROM information_schema.tables 
        WHERE table_schema NOT IN ('information_schema', 'performance_schema', 'mysql', 'test', 'sys') 
       and engine <> 'tokudb'  #tokudb存储引擎引起
          ORDER BY total_size DESC 
        LIMIT {},{};""".format(
