### ISSUE TITLE
docker 版（2.0）SQLTuning运行时无法解析带有临时表的sql

### ISSUE THREAD

**Issue by hanbing5210** [hhyo/archer#2038]
### 重现步骤

```sql
            select activity_id,audit_status from (SELECT
               acr.audit_status,
              acr.activity_id
            FROM
             a as  acr 
            WHERE
              acr.audit_type = 1
              
              order by 
              acr.create_time) as b 
              group by
              b.activity_id
```
优化的sql示例

### 预期外的结果

![Uploading image.png…]()

### 日志文本

```shell
2023-01-29 15:19:16 [2023-01-29 15:19:16,843][MainThread:140273746122560][task_id:default][mysql.py:357][WARNING]- MySQL语句执行报错，语句：show create table `b`;，错误信息Traceback (most recent call last):
2023-01-29 15:19:16   File "/opt/archery/sql/engines/mysql.py", line 341, in query
2023-01-29 15:19:16     effect_row = cursor.execute(sql)
2023-01-29 15:19:16   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
2023-01-29 15:19:16     res = self._query(query)
2023-01-29 15:19:16   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
2023-01-29 15:19:16     db.query(q)
2023-01-29 15:19:16   File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
2023-01-29 15:19:16     _mysql.connection.query(self, query)
2023-01-29 15:19:16 MySQLdb._exceptions.ProgrammingError: (1146, "Table 'njbankdevelop.b' doesn't exist")
2023-01-29 15:19:16
```

### 版本

2.0

### 部署方式

Docker

**Comment by hanbing5210** [comment]
![image](https://user-images.githubusercontent.com/32626294/215311533-e839c1c8-2150-4a41-80ea-d4bc4c2add70.png)
补充前端错误提示

**Comment by hhyo** [comment]
表解析存在一些缺陷，暂时无法处理

**Comment by hanbing5210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
