### ISSUE TITLE
oracle实例报：Object of type LOB is not JSON serializable

### ISSUE THREAD

**Issue by liuxiaoxiong** [hhyo/archer#2072]
### 重现步骤

关联的oracle实例报以下错误：
在我执行select table的过程中报错：
Object of type LOB is not JSON serializable
一旦oracle表里面有这个字段：CNLOB就会报错。

### 预期外的结果

关联的oracle实例报以下错误：
在我执行select table的过程中报错：
Object of type LOB is not JSON serializable
一旦oracle表里面有这个字段：CNLOB就会报错。

### 日志文本

```shell
[2023-03-06 16:52:09,890][MainThread:140709383280448][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/archery/common/utils/extend_json_encoder.py", line 76, in default
    return convert(obj)
  File "/usr/local/python3/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/archery/common/utils/extend_json_encoder.py", line 13, in convert
    raise TypeError('can not convert type')
TypeError: can not convert type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/query.py", line 176, in query
    return HttpResponse(json.dumps(result, use_decimal=False, cls=ExtendJSONEncoderFTime, bigint_as_string=True),
  File "/opt/venv4archery/lib/python3.9/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/opt/venv4archery/lib/python3.9/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/venv4archery/lib/python3.9/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/opt/archery/common/utils/extend_json_encoder.py", line 78, in default
    return super(ExtendJSONEncoderFTime, self).default(obj)
  File "/opt/venv4archery/lib/python3.9/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type LOB is not JSON serializable
```

### 版本

1.8.5

### 部署方式

Docker

**Comment by xkyang1** [comment]
我本地部署，也遇到了该问题，版本1.10 ，不知道新版本这个问题解决了没
