### ISSUE TITLE
sql上线，delete语句和insert语句同时提交，执行时会报错

### ISSUE THREAD

**Issue by Leif160519** [hhyo/archer#2083]
### 重现步骤

1.sql上线提交delete和insert语句
![image](https://user-images.githubusercontent.com/19452903/225551160-82b5342e-4315-419b-8953-43ad674cdba0.png)
2.审核通过
3.执行时报错

### 预期外的结果

![image](https://user-images.githubusercontent.com/19452903/225550598-2af2b500-7a09-4551-92ed-c57379f818ec.png)

### 日志文本

```shell
: Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.9/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/opt/archery/sql/utils/execute_sql.py", line 39, in execute
execute_engine = get_engine(instance=workflow_detail.instance)
File "/opt/archery/sql/engines/__init__.py", line 173, in get_engine
return MysqlEngine(instance=instance)
File "/opt/archery/sql/engines/mysql.py", line 25, in __init__
super().__init__(instance=instance)
File "/opt/archery/sql/engines/__init__.py", line 24, in __init__
self.ssh = SSHConnection(
File "/opt/archery/sql/utils/ssh_tunnel.py", line 43, in __init__
self.server.start()
File "/opt/venv4archery/lib/python3.9/site-packages/sshtunnel.py", line 1291, in start
self._create_tunnels()
File "/opt/venv4archery/lib/python3.9/site-packages/sshtunnel.py", line 1131, in _create_tunnels
self._connect_to_gateway()
File "/opt/venv4archery/lib/python3.9/site-packages/sshtunnel.py", line 1357, in _connect_to_gateway
self._transport.connect(hostkey=self.ssh_host_key,
File "/opt/venv4archery/lib/python3.9/site-packages/paramiko/transport.py", line 1346, in connect
self.start_client()
File "/opt/venv4archery/lib/python3.9/site-packages/paramiko/transport.py", line 699, in start_client
raise e
File "/opt/venv4archery/lib/python3.9/site-packages/paramiko/transport.py", line 2110, in run
ptype, m = self.packetizer.read_message()
File "/opt/venv4archery/lib/python3.9/site-packages/paramiko/packet.py", line 459, in read_message
header = self.read_all(self.__block_size_in, check_rekey=True)
File "/opt/venv4archery/lib/python3.9/site-packages/paramiko/packet.py", line 303, in read_all
raise EOFError()
EOFError
```
```


### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

_No response_

**Comment by hhyo** [comment]
看起来是隧道连接的问题，和语句无关

**Comment by Leif160519** [comment]
> 看起来是隧道连接的问题，和语句无关

Ok ,我再观察观察
