### ISSUE TITLE
pt-osc的问题

### ISSUE THREAD

**Issue by jimsoft1000** [hhyo/archer#2118]
### 重现步骤

设置osc_recursion_method = none参数，在线查询菜单，查询SQL时，报以下错误

### 预期外的结果

配置pt-osc

### 日志文本

```shell
[2023-04-10 13:55:17,151][MainThread:139948375611200][task_id:default][data_masking.py:50][WARNING]- 数据脱敏异常，错误信息：Traceback (most recent call last):
  File "/opt/archery/sql/utils/data_masking.py", line 28, in data_masking
    select_list = inception_engine.query_data_masking(instance=instance, db_name=db_name, sql=sql)
  File "/opt/archery/sql/engines/goinception.py", line 180, in query_data_masking
    query_result = self.query(db_name=db_name, sql=sql)
  File "/opt/archery/sql/engines/goinception.py", line 132, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 36, in get_connection
    self.conn = MySQLdb.connect(host=go_inception_host, port=go_inception_port, charset='utf8mb4',
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'goinception' (2)")
```

### 版本

1.8.5

### 部署方式

Docker

**Comment by jimsoft1000** [comment]
设置此参数，修改大表时，不检查从库

**Comment by jimsoft1000** [comment]
貌似设置成osc_recursion_method = "none" ，加上引号，就没有问题
