### ISSUE TITLE
执行DDL，报错（1406.“Data too long for column 'workflow_name' at row 1”）

### ISSUE THREAD

**Issue by maxianwei** [hhyo/archer#2123]
### 重现步骤

1.某个开发使用自己的archery账号突然无法执行SQL上线操作了，提交上线工单时报错1406.“Data too long for column 'workflow_name' at row 1”）  查看权限是正常的
2.我用管理员账号执行开发的sql语句是正常的， 其他开发人员的SQL上线功能也正常
3.

### 预期外的结果

报错如下：
<img width="1126" alt="企业微信截图_fd735fe5-983d-4ce9-bdf6-f6138c8dcf76" src="https://user-images.githubusercontent.com/34542869/232439744-270b0056-9b7a-4e6a-8bc4-fa6fed7e5e78.png">

执行下面的ddl语句报错，单独执行也报错：
-- 新增字段
alter table family_virtual_space add column `init_flag` tinyint NOT NULL DEFAULT 0 COMMENT '虚拟空间创建标识(最多一次，不可更新)，0-未初始化，1-已初始化' after updated_by;
-- 更新已有数据
update family_virtual_space set init_flag = 1 where map_resource is not null;

### 日志文本

```shell
archery.log
[2023-04-17 16:44:36,450][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721076.4441288
[2023-04-17 16:45:29,415][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721129.4093812
[2023-04-17 16:47:33,437][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721253.4306676
[2023-04-17 16:47:53,974][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721273.9093335
[2023-04-17 16:49:48,433][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721388.4089196
[2023-04-17 16:50:27,373][MainThread:139885425510208][task_id:default][mysql.py:269][WARNING]- MySQL语句执行报错，语句：explain select
 id,
  a.order_code '订单编码',
  a.quantity '数量',
  a.sku_id 'skuid',
  b.name '商品名称',
  a.unit '单位',
  a.ware_type '0:硬件；1：软件',
  a.payment / 100 '单价',
  a.total_price / 100 '总价',
  a.sale_corporation_code '销售主体'
from
  vm_settle.invoice_sku a,
  vm_wares.prod_sku b
where
  a.order_code in ('22022447237','22022122658','22011233718','22011248521','21120969657','21111068987','21102049773','21092279754','21092226268','21091753193','21081533223','21081529962','21081028164','21081065872','21081031685','21072321353','21072026264','21071379862','21071318439','21071348675','21061342982','21050931488','21050884433','21042469213','21042011418','21020218661','21012272455','21010896923','20121642242','20112414416','20112427955','20112078649','20112047952','20090197687','20090125913','20081089816','20072381687','20072389179','20071893974','20062931531','20061837336','20052784284','20052699933','20052641137','20052639545','20052673178','20051996113','20051919375','20051539158','20051436965','20051499594','20051373387','20051148566','20050649649','20050648286','20043089322','20042386922','20042116479','20042094539','20040873853','20040648248','20032751895','20032685936','20032532362','20032383474','20031547713','20031328727','20030481694','20030491333','20022853745','20011245963','20010941664','20010744796','20010631415')
  and a.status = 1
  and a.sku_id = b.id，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 258, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (1052, "Column 'id' in field list is ambiguous")

[2023-04-17 16:50:34,334][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721434.3258882
[2023-04-17 16:51:48,262][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721508.2566032
[2023-04-17 16:54:10,293][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- ���除schedule：query-1681721650.2297063
[2023-04-17 16:54:20,952][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721660.889977
[2023-04-17 16:55:27,325][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721727.2649426
[2023-04-17 16:56:30,492][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721790.4271731
[2023-04-17 16:58:24,893][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681721904.8877223
[2023-04-17 17:05:34,059][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681722334.05346
[2023-04-17 17:12:08,845][MainThread:139885425510208][task_id:default][tasks.py:38][DEBUG]- 删除schedule：query-1681722728.8397863

goinception log
[2023-04-17 17:08:56,670][MainThread:140656599230272][task_id:default][sql_workflow.py:225][ERROR]- 提交工单报错，错误信息：Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'workflow_name' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/sql/sql_workflow.py", line 196, in submit
    sql_workflow = SqlWorkflow.objects.create(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'workflow_name' at row 1")
```

### 版本

1.8.4

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

数据库为腾讯云云数据库 5.7版本

**Comment by hhyo** [comment]
工单名称超长了，精简一下就行

**Comment by maxianwei** [comment]
看了下源码，限制50个字符，这块建议可以调大一些
