### ISSUE TITLE
archery:v1.9.1配置ldap后登录失败，500 internal server error

### ISSUE THREAD

**Issue by jingj38765** [hhyo/archer#2127]
### 重现步骤

1.ldap配置如下
ENABLE_LDAP = True
if ENABLE_LDAP:
    import ldap
    from django_auth_ldap.config import LDAPSearch
    AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',  # 配置为先使用LDAP认证，如通过认证则不再使用后面的认证方式
        'django.contrib.auth.backends.ModelBackend',  # django系统中手动创建的用户也可使用，优先级靠后。注意这2行的顺序
    )

    AUTH_LDAP_SERVER_URI = 'ldap://10.164.xxxx.xxx:389'
   # AUTH_LDAP_USER_DN_TEMPLATE = "cn=%(user)s,ou=xxx,dc=xxx,dc=xxx"
    AUTH_LDAP_BIND_DN = 'cn=ldap_archery,dc=haiermoney,dc=com'
    AUTH_LDAP_BIND_PASSWORD = 'xxxxxx'
    AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=HM,dc=haiermoney,dc=com',ldap.SCOPE_SUBTREE,'(uid=%(user)s)',)
    AUTH_LDAP_ALWAYS_UPDATE_USER = True  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "cn",
        "display": "displayname",
        "email": "mail"
    }
~                                

### 预期外的结果

500 internal server error

### 日志文本

```shell
[2023-04-20 16:22:42,204][MainThread:140151187126080][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/archery/common/auth.py", line 69, in authenticate
    user = Users.objects.get(username=username)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
sql.models.Users.DoesNotExist: Users matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/common/auth.py", line 118, in authenticate_entry
    result = new_auth.authenticate()
  File "/opt/archery/common/auth.py", line 71, in authenticate
    authenticated_user = self.challenge(username=username, password=password)
  File "/opt/archery/common/auth.py", line 56, in challenge
    user = authenticate(username=username, password=password)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/venv4archery/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 79, in <module>
    populate_user = django.dispatch.Signal("user","ldap_user")
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
```

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql:5.7

**Comment by lanheader** [comment]
File "/opt/archery/common/auth.py", line 56, in challenge
    user = authenticate(username=username, password=password)
这个文件第56行，你在这里打断点看下username和password的数据是否正常

**Comment by jingj38765** [comment]
> ```shell
> raise self.model.DoesNotExist(
> sql.models.Users.DoesNotExist: Users matching query does not exist.
> ```

账号密码是🆗的，好像是这里出了问题呢
raise self.model.DoesNotExist(
sql.models.Users.DoesNotExist: Users matching query does not exist.

**Comment by jingj38765** [comment]
已经解决。原因是绑定的cn路径没有写完整，
要写成，cn=aa,ou=a,ou=b,dc=c,dc=com
而不是，cn=aa,dc=c,dc=com

**Comment by FSerKevin** [comment]
老哥，我在seettings中配置后 重启archery容器后 前端页面就打不开是什么原因，求指教

**Comment by jingj38765** [comment]
> 老哥，我在seettings中配置后 重启archery容器后 前端页面就打不开是什么原因，求指教

老弟，你的配置和报错 贴出来

**Comment by FSerKevin** [comment]
![image](https://github.com/hhyo/Archery/assets/79827043/a9f3148e-ed16-470e-ab70-7c87473ace76)
老哥配置好了 前端页面没问题了 但登陆反复提示用户名密码不对

**Comment by FSerKevin** [comment]
> ![image](https://user-images.githubusercontent.com/79827043/240791944-a9f3148e-ed16-470e-ab70-7c87473ace76.png) 老哥配置好了 前端页面没问题了 但登陆反复提示用户名密码不对

已经搞定了

**Comment by FSerKevin** [comment]
> > 老哥，我在seettings中配置后 重启archery容器后 前端页面就打不开是什么原因，求指教
> 
> 老弟，你的配置和报错 贴出来

老哥，经过测试探索
已经搞定了

**Comment by jingj38765** [comment]
> > > 老哥，我在seettings中配置后 重启archery容器后 前端页面就打不开是什么原因，求指教
> > 
> > 
> > 老弟，你的配置和报错 贴出来
> 
> 老哥，经过测试探索 已经搞定了

太棒了。老弟。我也是最后自己摸索出来的。
