### ISSUE TITLE
mysql table查询权限管控无效-异常

### ISSUE THREAD

**Issue by cyin888** [hhyo/archer#2146]
### 重现步骤

1: 用户配置QA组权限不加红框中选项
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/29536747/236154392-f01b76f6-06eb-4548-b78e-927c9b3b1427.png">
2: mysql table查询权限审批正常
3: 对通过审批权限的table进行查询：select order_trade_no from d_order 

### 预期外的结果

执行异常：
<img width="820" alt="image" src="https://user-images.githubusercontent.com/29536747/236156269-9d8acb7d-384f-44f3-b670-6f3e5b6367d4.png">
代码：
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/29536747/236156810-492214ab-d90c-45b5-b544-d8cab3b4d00d.png">

### 日志文本

```shell
[2023-05-04 17:01:11,496][MainThread:139698220676928][task_id:default][query_privileges.py:94][ERROR]- 无法校验查询语句权限，mysql-test，select create_time from d_order，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 73, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 485, in _table_ref
    query_tree = engine.query_print(
  File "/opt/archery/sql/engines/goinception.py", line 181, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
  File "/opt/archery/sql/engines/goinception.py", line 150, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 42, in get_connection
    self.conn = MySQLdb.connect(
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
TypeError: connect() argument 1 must be str, not None
```

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL:5.7.36

**Comment by cyin888** [comment]
需要进行goInception配置

**Comment by cyin888** [comment]
OK
