### ISSUE TITLE
v1.9.1 oracle审核 TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by taijiyouxia** [hhyo/archer#2168]
### 重现步骤

1 部署v1.9.1后，审核oracle的sql，随便一条sql语句，如create table test111(id int); 会报如下的错误：
[2023-05-23 16:44:22,753][Thread-2:139803802728192][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table test111(id int);，错误信息Traceback (most recent call last):
  File "/backup/Archery-1.9.1/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

2 用v1.8.5版本的oracle.py文件，发现审核正常

### 预期外的结果

1 部署v1.9.1后，审核oracle的sql，随便一条sql语句，如create table test111(id int); 会报如下的错误：
[2023-05-23 16:44:22,753][Thread-2:139803802728192][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table test111(id int);，错误信息Traceback (most recent call last):
  File "/backup/Archery-1.9.1/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

2 用v1.8.5版本的oracle.py文件，发现审核正常

### 日志文本

```shell
[2023-05-23 16:44:22,753][Thread-2:139803802728192][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table test111(id int);，错误信息Traceback (most recent call last):
  File "/backup/Archery-1.9.1/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### 版本

1.9.1

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

oracle：11.2.0.4
用v1.8.5版本的oracle.py文件替换后，发现审核正常

**Comment by taijiyouxia** [comment]
#2132 解决

**Comment by tonyhu214** [comment]
@taijiyouxia  #2262  我再这个issue 里面进行了fix。
