### ISSUE TITLE
升级到1.9.1部分功能打开报错500

### ISSUE THREAD

**Issue by sckghost** [hhyo/archer#2206]
### 重现步骤

从1.7.1升级到1.9.1服务和数据库流程正常，导入数据后，部分功能报错500，日志如下：

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/7287929/e15a6640-6329-43ce-a035-b21286ae67e7)

### 日志文本

```shell
[2023-07-13 16:18:23,954][MainThread:140619621508928][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'resource_group.qywx_webhook' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1931, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/options.py", line 834, in get_changelist_instance
    return ChangeList(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 122, in __init__
    self.queryset = self.get_queryset(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 503, in get_queryset
    ) = self.get_filters(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 182, in get_filters
    spec = field_list_filter_class(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/filters.py", line 175, in create
    return list_filter_class(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/filters.py", line 188, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/admin/filters.py", line 225, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 980, in get_choices
    return (blank_choice if include_blank else []) + [
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'resource_group.qywx_webhook' in 'field list'")
```

### 版本

1.9.1

### 部署方式

Docker

**Comment by nick2wang** [comment]
升级后需要进行数据库变更，执行src/init_sql下的变更sql
![image](https://github.com/hhyo/Archery/assets/33473924/cf71b278-47de-4058-84ab-9ba1cb4c70b6)
