### ISSUE TITLE
请对问题进行简要的描述

### ISSUE THREAD

**Issue by huxiangquan** [hhyo/archer#2222]
### 重现步骤

1，k8s helm安装，更换了namespace
helm install archery douban/archery -f values.yaml -n archery-ns

### 预期外的结果

1，无法启动init-mysql，日志提示无法连接。手工修改初始脚本后能连接成功。
2，无法连接redis，日志提示连接redis的服务名是 Error 111 connecting to archery-redis:6379. Connection refused.而默认创建的服务名是：
archery-redis-master
3，修改服务名后，连接提示密码不正确。（全默认配置）
 WRONGPASS invalid username-password pair or user is disabled.

### 日志文本

```shell
切换python运行环境
修改重定向端口
启动nginx
收集所有的静态文件到STATIC_ROOT
启动Django Q cluster
启动服务
[2023-07-26 17:50:14,100][MainThread:140379879262016][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 111 connecting to archery-redis:6379. Connection refused.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 125, in _wrapped_view
    result = middleware.process_request(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/middleware/cache.py", line 158, in process_request
    cache_key = get_cache_key(request, self.key_prefix, "GET", cache=self.cache)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/cache.py", line 390, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to archery-redis:6379. Connection refused.
/opt/venv4archery/lib/python3.9/site-packages/django/views/debug.py:473: ExceptionCycleWarning: Cycle in the exception chain detected: exception 'Error 111 connecting to archery-redis:6379. Connection refused.' encountered again.
  warnings.warn(
[2023-07-26 17:51:18,603][MainThread:140379879262016][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: WRONGPASS invalid username-password pair or user is disabled.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 125, in _wrapped_view
    result = middleware.process_request(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/middleware/cache.py", line 158, in process_request
    cache_key = get_cache_key(request, self.key_prefix, "GET", cache=self.cache)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/cache.py", line 390, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/opt/venv4archery/lib/python3.9/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/opt/venv4archery/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled.
/opt/venv4archery/lib/python3.9/site-packages/django/views/debug.py:473: ExceptionCycleWarning: Cycle in the exception chain detected: exception 'WRONGPASS invalid username-password pair or user is disabled.' encountered again.
  warnings.warn(
```

### 版本

1.9.1

### 部署方式

K8S

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql5.7.redis6

部署的问题较多
另外请给一份配置外部数据库和redis的模板。
这个文件不知道该如何配置：
假定：
redis:  192.168.233.2:6370  密码 123redis
mysql: 192.168.233.2:3306 密码 123mysql

```
# subcharts redis
redis:
  embedded: true
  # url: "redis://127.0.0.1:6379/0"
  # urlSecret: ""
  # urlSecretKey: "CACHE_URL"
  # dingdingUrl: "redis://127.0.0.1:6379/1"
  # dingdingUrlSecret: ""
  # dingdingUrlSecretKey: "DINGDING_CACHE_URL"
  # embedded 为 false, 会使用外部的 redis, 下方的 redis 就不会生效
  architecture: standalone
  auth:
    password: "REDIS_PASSWORD"
  master:
    persistence:
      enabled: false
      size: 8Gi
      # storageClass: ""

# subcharts mysql
mysql:
  embedded: true
  # url: "mysql://root:@127.0.0.1:3306/archery"
  # urlSecret: ""
  # urlSecretKey: "DATABASE_URL"
  # embedded 为 false时, 会使用外部的 mysql, 下方的 mysql 配置不会生效
```

**Comment by LeoQuote** [comment]
外部数据库和redis的配置就在 注释中，去掉注释即可， url代表是明文连接串，urlSecret 为预先配置好的secret，secretkey为secret中使用的文件名

**Comment by huxiangquan** [comment]
> 外部数据库和redis的配置就在 注释中，去掉注释即可， url代表是明文连接串，urlSecret 为预先配置好的secret，secretkey为secret中使用的文件名

好的，安装这步已经调通了。
