### ISSUE TITLE
配置邮箱测试链接报错

### ISSUE THREAD

**Issue by Lihy6472** [hhyo/archer#2297]
### 重现步骤

* docker部署，在系统管理>配置项管理>工单通知>mail中配置了邮箱、smtp地址、账号密码，测试链接报错

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/116717391/78efc6d2-3fd2-4f43-a1ac-1f6866c450a5)

### 日志文本

```shell
* docker logs -f archery：

[2023-09-13 17:34:59,279][MainThread:140210683098944][task_id:default][sendmsg.py:133][ERROR]- 邮件推送失败
Traceback (most recent call last):
  File "/opt/archery/common/utils/sendmsg.py", line 124, in send_email
    server.login(self.MAIL_REVIEW_FROM_ADDR, self.MAIL_REVIEW_FROM_PASSWORD)
  File "/usr/local/python3/lib/python3.9/smtplib.py", line 730, in login
    raise SMTPException("No suitable authentication method found.")
smtplib.SMTPException: No suitable authentication method found.
```
```


### 版本

1.10

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

_No response_

**Comment by Grain-Yu** [comment]
发送邮件服务器用的加密协议是STARTTLS?
如果是这样的话，目前不支持哦，需要调整代码的。参考https://www.cnblogs.com/muxinyue/p/5261149.html
