### ISSUE TITLE
慢日志统计页面无法展现SQL历史趋势图

### ISSUE THREAD

**Issue by Grain-Yu** [hhyo/archer#2330]
### 重现步骤

SQL优化->慢查日志->慢日志统计页面，展开单条语句的详情页面，无法展现SQL历史趋势图

### 预期外的结果

页面提示“Internal Server  Error”

### 日志文本

```shell
archery的日志：
[2023-10-13 09:20:53,089][MainThread:140312554125120][task_id:django.request][log.py:224][ERROR]- Internal Server Error: /slowquery/report/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 209, in report
    checksum = MySQLdb.escape_string(checksum).decode("utf-8")
AttributeError: module 'MySQLdb' has no attribute 'escape_string'
```

### 版本

1.10.0

### 部署方式

Docker

**Comment by Grain-Yu** [comment]
mysqlclient的版本问题，2.1.0以后移除了这个方法：
Remove escape() and escape_string() from MySQLdb package.
https://github.com/PyMySQL/mysqlclient/blob/91c04282eac46ce2e5380be58e262d817faab566/HISTORY.rst#whats-new-in-210

**Comment by Grain-Yu** [comment]
https://github.com/hhyo/Archery/pull/2331#issuecomment-1776311859
按这个方法处理

**Comment by feiazifeiazi** [comment]
太坑。方法都没了，得后知后觉。 还是强类型语言好。python语言如何提前发现这个问题呢？

**Comment by LeoQuote** [comment]
这没办法提前发现，只能多写测试
