### ISSUE TITLE
v1.10.0初始化报错找不到gssapi相应子模块包

### ISSUE THREAD

**Issue by hsjz81** [hhyo/archer#2381]
### 重现步骤

**v1.10.0使用python3.8和3.9初始化报错，找不到gssapi相应的模块包，检查发现gssapi/raw/目录下都是以pyi后缀结尾的文件导致导入模块失败
解决：**
1、使用pip把gssapi包从高到底的各个版本都安装了一遍都不行
2、使用try:方式跳过对应错误，最终没有成功
3、下载Archery-1.9.1版本安装成功

**1、系统环境**
CentOS Linux release 8.4.2105

**2、python3.9安装相关依赖包**
[root@localhost system-admin]# docker exec -it archery /bin/bash
[root@862687c17c3d /]# pip3.9 list
Package                       Version
----------------------------- ------------
aiohttp                       3.8.6
aiosignal                     1.3.1
alibabacloud-credentials      0.3.2
alibabacloud-dysmsapi20170525 2.0.9
alibabacloud-endpoint-util    0.0.3
alibabacloud-gateway-spi      0.0.1
alibabacloud-openapi-util     0.2.2
alibabacloud-tea              0.3.3
alibabacloud-tea-openapi      0.3.7
alibabacloud-tea-util         0.3.11
alibabacloud-tea-xml          0.0.2
aliyun-python-sdk-core-v3     2.13.33
aliyun-python-sdk-rds         2.1.1
arrow                         1.3.0
asgiref                       3.7.2
async-timeout                 4.0.3
attrs                         23.1.0
bcrypt                        4.0.1
blessed                       1.20.0
cassandra-driver              3.28.0
certifi                       2023.7.22
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
clickhouse-driver             0.2.6
cryptography                  41.0.5
cx-Oracle                     7.3.0
decorator                     5.1.1
Django                        4.1.10
django-auth-dingding          0.0.2
django-auth-ldap              4.1.0
django-environ                0.8.1
django-filter                 21.1
django-mirage-field           1.4.0
django-picklefield            3.1
django-q                      1.3.9
django-redis                  5.2.0
djangorestframework           3.13.1
djangorestframework-simplejwt 5.2.0
docopt                        0.6.2
drf-spectacular               0.22.0
frozenlist                    1.4.0
future                        0.18.3
geomet                        0.2.1.post1
greenlet                      3.0.1
gssapi                        1.8.3
gunicorn                      20.0.4
idna                          3.4
inflection                    0.5.1
Jinja2                        3.1.2
jmespath                      0.10.0
josepy                        1.14.0
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
MarkupSafe                    2.1.3
mozilla-django-oidc           3.0.0
multidict                     6.0.4
mybatis-mapper2sql            0.1.9
mysql-replication             0.22
mysqlclient                   2.2.0
numpy                         1.26.1
pandas                        1.5.3
paramiko                      3.3.1
parsedatetime                 2.4
phoenixdb                     1.2.1
Pillow                        9.3.0
pip                           20.2.4
ply                           3.11
prettytable                   3.9.0
protobuf                      4.25.0
psycopg2-binary               2.9.9
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pycparser                     2.21
pycryptodome                  3.10.1
pyecharts                     1.9.1
pyi                           0.1.0
PyJWT                         2.8.0
pymongo                       3.11.0
PyMySQL                       0.9.3
PyNaCl                        1.5.0
pyodbc                        4.0.39
pyodps                        0.11.4.1
pyOpenSSL                     23.3.0
pyotp                         2.6.0
python-dateutil               2.8.1
python-ldap                   3.4.3
pytz                          2023.3.post1
PyYAML                        6.0.1
qrcode                        7.3.1
redis                         3.5.3
referencing                   0.30.2
requests                      2.31.0
requests-gssapi               1.2.3
rpds-py                       0.12.0
Schema-Object                 0.5.11
Schema-Sync                   0.9.7
setuptools                    50.3.2
simplejson                    3.17.2
six                           1.16.0
SQLAlchemy                    2.0.23
sqlparse                      0.4.4
sshtunnel                     0.1.5
supervisor                    4.1.0
tencentcloud-sdk-python       3.0.656
tqdm                          4.66.1
types-python-dateutil         2.8.19.14
typing-extensions             4.8.0
tzlocal                       5.2
uritemplate                   4.1.1
urllib3                       2.0.7
wcwidth                       0.2.9
yarl                          1.9.2
[root@862687c17c3d /]# 

**3、初始数据时报错**

[root@862687c17c3d Archery-1.10.0]# python3.9 manage.py makemigrations sql
import local settings failed, ignored
Traceback (most recent call last):
  File "/app/Archery-1.10.0/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/Archery-1.10.0/archery/urls.py", line 7, in <module>
    path("api/", include(("sql_api.urls", "sql_api"), namespace="sql_api")),
  File "/usr/local/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/Archery-1.10.0/sql_api/urls.py", line 14, in <module>
    from . import api_user, api_instance, api_workflow
  File "/app/Archery-1.10.0/sql_api/api_user.py", line 4, in <module>
    from .serializers import (
  File "/app/Archery-1.10.0/sql_api/serializers.py", line 19, in <module>
    from sql.engines import get_engine
  File "/app/Archery-1.10.0/sql/engines/__init__.py", line 224, in <module>
    engine_map = get_engine_map()
  File "/app/Archery-1.10.0/sql/engines/__init__.py", line 219, in get_engine_map
    engine = getattr(importlib.import_module(module), o)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/Archery-1.10.0/sql/engines/phoenix.py", line 7, in <module>
    import phoenixdb
  File "/usr/local/lib/python3.9/site-packages/phoenixdb/__init__.py", line 17, in <module>
    import gssapi
  File "/usr/local/lib64/python3.9/site-packages/gssapi/__init__.py", line 31, in <module>
    from gssapi.raw.types import NameType, RequirementFlag, AddressType  # noqa
  File "/usr/local/lib64/python3.9/site-packages/gssapi/raw/__init__.py", line 50, in <module>
    from gssapi.raw.creds import *  # noqa
ModuleNotFoundError: No module named 'gssapi.raw.creds'
[root@862687c17c3d Archery-1.10.0]# 

查看/usr/local/lib64/python3.9/site-packages/gssapi/raw/目录下都是以pyi后缀结尾的文件

-rw-r--r-- 1 root root  3706 Nov  8 01:58 __init__.py
drwxr-xr-x 2 root root  4096 Nov  8 01:58 __pycache__
drwxr-xr-x 3 root root  4096 Nov  8 01:58 _enum_extensions
-rw-r--r-- 1 root root   960 Nov  8 01:58 chan_bindings.pyi
-rw-r--r-- 1 root root  6124 Nov  8 01:58 creds.pyi
-rw-r--r-- 1 root root  1689 Nov  8 01:58 exceptions.pyi
-rw-r--r-- 1 root root   919 Nov  8 01:58 ext_cred_imp_exp.pyi
-rw-r--r-- 1 root root  4917 Nov  8 01:58 ext_cred_store.pyi
-rw-r--r-- 1 root root  5133 Nov  8 01:58 ext_dce.pyi
-rw-r--r-- 1 root root  1859 Nov  8 01:58 ext_dce_aead.pyi
-rw-r--r-- 1 root root  3269 Nov  8 01:58 ext_ggf.pyi
-rw-r--r-- 1 root root  2490 Nov  8 01:58 ext_iov_mic.pyi
-rw-r--r-- 1 root root  7602 Nov  8 01:58 ext_krb5.pyi
-rw-r--r-- 1 root root  1438 Nov  8 01:58 ext_password.pyi
-rw-r--r-- 1 root root  1845 Nov  8 01:58 ext_password_add.pyi
-rw-r--r-- 1 root root   721 Nov  8 01:58 ext_rfc4178.pyi
-rw-r--r-- 1 root root  1762 Nov  8 01:58 ext_rfc5587.pyi
-rw-r--r-- 1 root root  1434 Nov  8 01:58 ext_rfc5588.pyi
-rw-r--r-- 1 root root   962 Nov  8 01:58 ext_rfc5801.pyi
-rw-r--r-- 1 root root  5396 Nov  8 01:58 ext_rfc6680.pyi
-rw-r--r-- 1 root root     0 Nov  8 01:58 ext_rfc6680_comp_oid.pyi
-rw-r--r-- 1 root root  3462 Nov  8 01:58 ext_s4u.pyi
-rw-r--r-- 1 root root  1765 Nov  8 01:58 ext_set_cred_opt.pyi
-rw-r--r-- 1 root root     0 Nov  8 01:58 mech_krb5.pyi
-rw-r--r-- 1 root root  4723 Nov  8 01:58 message.pyi
-rw-r--r-- 1 root root  4555 Nov  8 01:58 misc.pyi
-rw-r--r-- 1 root root  6646 Nov  8 01:58 named_tuples.py
-rw-r--r-- 1 root root  4109 Nov  8 01:58 names.pyi
-rw-r--r-- 1 root root  1360 Nov  8 01:58 oids.pyi
-rw-r--r-- 1 root root 10241 Nov  8 01:58 sec_contexts.pyi
-rw-r--r-- 1 root root  5005 Nov  8 01:58 types.pyi
[root@862687c17c3d Archery-1.10.0]# 

试着使用try方式跳过错误

from gssapi.raw.creds import *  # noqa
from gssapi.raw.message import *  # noqa
from gssapi.raw.misc import *  # noqa
from gssapi.raw.exceptions import *  # noqa
from gssapi.raw.names import *  # noqa
from gssapi.raw.sec_contexts import *  # noqa
from gssapi.raw.oids import *  # noqa
from gssapi.raw.types import *  # noqa
from gssapi.raw.chan_bindings import *  # noqa

改为

try:
    from gssapi.raw.creds import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.message import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.misc import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.exceptions import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.names import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.sec_contexts import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.oids import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library
try:
    from gssapi.raw.types import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library

  File "/usr/local/lib64/python3.9/site-packages/gssapi/__init__.py", line 31, in <module>
    from gssapi.raw.types import NameType, RequirementFlag, AddressType  # noqa
ModuleNotFoundError: No module named 'gssapi.raw.types'

from gssapi.raw.types import NameType, RequirementFlag, AddressType  # noqa
from gssapi.raw.types import MechType, IntEnumFlagSet  # noqa
from gssapi.raw.oids import OID  # noqa

改为

try:
    from gssapi.raw.types import NameType, RequirementFlag, AddressType  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library

try:
    from gssapi.raw.types import MechType, IntEnumFlagSet  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library

try:
    from gssapi.raw.oids import OID  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library

    from gssapi.raw.chan_bindings import *  # noqa
except ImportError:
    pass  # no s4u support in the system's GSSAPI library

  File "/usr/local/lib64/python3.9/site-packages/gssapi/creds.py", line 3, in <module>
    from gssapi.raw import creds as rcreds
ImportError: cannot import name 'creds' from 'gssapi.raw' (/usr/local/lib64/python3.9/site-packages/gssapi/raw/__init__.py)

  File "/usr/local/lib64/python3.9/site-packages/gssapi/names.py", line 4, in <module>
    from gssapi.raw import names as rname
ImportError: cannot import name 'names' from 'gssapi.raw' (/usr/local/lib64/python3.9/site-packages/gssapi/raw/__init__.py)

  File "/usr/local/lib64/python3.9/site-packages/gssapi/_utils.py", line 7, in <module>
    from gssapi.raw.misc import GSSError
ModuleNotFoundError: No module named 'gssapi.raw.misc'

**最终还是报错**

  File "/usr/local/lib64/python3.9/site-packages/gssapi/creds.py", line 24, in <module>
    from gssapi import names
  File "/usr/local/lib64/python3.9/site-packages/gssapi/names.py", line 27, in <module>
    class Name(rname.Name):
NameError: name 'rname' is not defined

### 预期外的结果

请作者老师机们，帮忙看看这个问题如何解决

谢谢

### 版本

1.10.0

### 部署方式

手工部署

**Comment by LeoQuote** [comment]
你用不用 phenixdb 呀？ 不用的话就不要启用，就不会报这个错了

https://github.com/hhyo/Archery/blob/2a42d5c0c4892246a4db75742e43df00f6405267/archery/settings.py#L41 覆盖这个配置，只用启用你想用的就行了，环境变量或者local_settings 覆盖都行

**Comment by hsjz81** [comment]
想过去掉phenixdb配置，但想知道能为什么我就配置不上？gssapi所有版本我都安装过了

**Comment by LeoQuote** [comment]
你可以自己去探索, 我也不知道具体你的机器上发生了什么. 欢迎 pr
