### ISSUE TITLE
会话管理中查看RDS的进程状态报错

### ISSUE THREAD

**Issue by arron-6z** [hhyo/archer#2487]
### 重现步骤

对于RDS在实例管理->会话管理下查看进行状态，top表空间等均有报错，报错信息见下面的截图及日志信息。

### 预期外的结果

![1705646323026](https://github.com/hhyo/Archery/assets/67582106/35b6ddec-97ae-45f6-a49a-6a163b440a15)

### 日志文本

```shell
[2024-01-19 14:37:49,109][MainThread:139768341038912][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/db_diagnostic.py", line 35, in process
    query_result = query_engine.processlist(command_type)
  File "/opt/archery/sql/engines/cloud/aliyun_rds.py", line 27, in processlist
    process_info = Aliyun(rds=instance_info).RequestServiceOfCloudDBA(
  File "/opt/archery/common/utils/aliyun_sdk.py", line 96, in RequestServiceOfCloudDBA
    result = self.request_api(request, values)
  File "/opt/archery/common/utils/aliyun_sdk.py", line 33, in request_api
    result = self.clt.do_action_with_exception(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/aliyunsdkcore/client.py", line 476, in do_action_with_exception
    raise exception
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 404 Error:InvalidAction.NotFound Specified api is not found, please check your url and method. RequestID: 922B3687-B92D-5A83-8809-235ACBA9CFCE

[2024-01-19 14:37:54,216][MainThread:139768341038912][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/db_diagnostic.py", line 35, in process
    query_result = query_engine.processlist(command_type)
  File "/opt/archery/sql/engines/cloud/aliyun_rds.py", line 27, in processlist
    process_info = Aliyun(rds=instance_info).RequestServiceOfCloudDBA(
  File "/opt/archery/common/utils/aliyun_sdk.py", line 96, in RequestServiceOfCloudDBA
    result = self.request_api(request, values)
  File "/opt/archery/common/utils/aliyun_sdk.py", line 33, in request_api
    result = self.clt.do_action_with_exception(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/aliyunsdkcore/client.py", line 476, in do_action_with_exception
    raise exception
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 404 Error:InvalidAction.NotFound Specified api is not found, please check your url and method. RequestID: B3AE933D-C3EB-54CE-A423-22EF3DE4ED33
```

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
我这边没有环境, 建议用 master 分支的版本重试一次, 如果还有问题, 欢迎提交 pr

**Comment by arron-6z** [comment]
> 我这边没有环境, 建议用 master 分支的版本重试一次, 如果还有问题, 欢迎提交 pr

已尝试，用master版本，这个python manage.py qcluster服务起不来，页面打不开，报内部错误

**Comment by LeoQuote** [comment]
python manage.py migrate
