### ISSUE TITLE
archery1.10 提交工单流程结束，执行工单的时候后台报错 AttributeError: 'WSGIRequest' object has no attribute 'user' 并且工单一直处于排队中。

### ISSUE THREAD

**Issue by xkyang1** [hhyo/archer#2544]
### 重现步骤

1.普通用户上线SQL，提交oracle DDL，通过审批流程审批完成，我测试提交的是create table xxx
在审批流程中，某个任务详情页面，工单详情子页面，“审核/执行信息”列内容为 “
Json decode failed.执行结果Json解析失败, 请联系管理员”

然后上一页面的工单列表，工单状态都是“排队中”

2.该过程后台启动日志报错信息重复出现如下报错部分：
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 81, in __call__
    return super().__call__(environ, start_response)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 56, in get_response
    return response_for_exception(request, e)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 68, in response_for_exception
    response = get_exception_response(
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 167, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 185, in handle_uncaught_exception
    return callback(request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/software/Archery-v1.10.0/common/views.py", line 38, in server_error
    return HttpResponseServerError(render(request, template_name))
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/local/python3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/software/Archery-v1.10.0/common/utils/global_info.py", line 10, in global_info
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'

### 预期外的结果

无。

### 版本

1.10

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql5.7.16

**Comment by Grain-Yu** [comment]
这是一个已解决的bug：https://github.com/hhyo/Archery/pull/2513/commits/d6d0241f45de33538b06cce90118197303597090
用最新版的程序 ：）

**Comment by xkyang1** [comment]
这样的啊 ，好的
