### ISSUE TITLE
oracle select 报错： Object of type LOB is not JSON serializable 一旦oracle表里面有这个字段：CNLOB就会报错

### ISSUE THREAD

**Issue by xkyang1** [hhyo/archer#2591]
### 重现步骤

1.版本archery1.10
2.配置oracle数据库实例
3.查询语句，只要涉及LOB类字段，就会报错
   界面弹出框信息 ： Internal Server Error

### 预期外的结果

略

### 日志文本

```shell
后台日志：
   Traceback (most recent call last):
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/software/Archery-v1.10.0/sql/query.py", line 191, in query
    json.dumps(
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/simplejson/__init__.py", line 381, in dumps
    return cls(
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = self.iterencode(o)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
  File "/software/Archery-v1.10.0/common/utils/extend_json_encoder.py", line 102, in default
    return super(ExtendJSONEncoderFTime, self).default(obj)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/simplejson/encoder.py", line 274, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type LOB is not JSON serializable
```

### 版本

1.10

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

其他软件版本都符合

**Comment by LeoQuote** [comment]
Duplicate of #2541
