### ISSUE TITLE
不同资源组用户提交的SQL上线内容，无法点进去查看详情语句

### ISSUE THREAD

**Issue by firehalt** [hhyo/archer#2632]
### 重现步骤

不同资源组用户提交的SQL上线内容，无法点进去查看详情语句，需要什么权限才能才看（给了所有权限都看不了）
比如：QA资源组成员提交的SQL上线语句，研发资源组成员点击进去查看详情就会出现403

### 预期外的结果

所有资源组的提交的语句都可以点击进去查看具体sql语句

### 日志文本

```shell
django.core.exceptions.PermissionDenied
[2024-05-09 17:04:39,274][MainThread:140459339388736][task_id:default][exception_logging_middleware.py:12][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/views.py", line 187, in detail
    raise PermissionDenied
django.core.exceptions.PermissionDenied

2024-05-09 17:04:39,274 - default - ERROR - Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/views.py", line 187, in detail
    raise PermissionDenied
django.core.exceptions.PermissionDenied

2024-05-09 17:04:39,286 - django.request - WARNING - Forbidden (Permission denied): /detail/3/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/views.py", line 187, in detail
    raise PermissionDenied
django.core.exceptions.PermissionDenied
```

### 版本

1.10.0

### 部署方式

Docker

**Comment by firehalt** [comment]
![Uploading 9999988.png…]()

**Comment by firehalt** [comment]
![9999988](https://github.com/hhyo/Archery/assets/29405113/d3814a21-3ebb-41a4-a162-9d29a23cc02d)

**Comment by feiazifeiazi** [comment]
@firehalt 研发组，有这个实例组的权限吗？ 研发组自己提交这个实例组的工单，他能看到的吧。

**Comment by hhyo** [comment]
资源组是用来做资源隔离的，设计上不允许跨资源组的访问，比较推荐的配置方式是

1. 资源组对应项目组，管理项目组内的所有资源
2. 权限组对应角色，相同角色具有相同的资源操作权限
