### ISSUE TITLE
无法指定Mongo实例操作：`'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.`

### ISSUE THREAD

**Issue by wang-xiaowu** [hhyo/archer#2641]
### 重现步骤

- 会话管理(进程状态)/在线查询/Sql上线 等等
- 选择mongo实例

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/44340137/c6a0e40f-be68-446c-bc4c-b396359eff0e)

### 日志文本

```shell
2024-05-14 10:19:35,920 - default - WARNING - mongodb获取连接信息错误，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mongo.py", line 1206, in current_op
    conn = self.get_connection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/archery/sql/engines/mongo.py", line 806, in get_connection
    self.conn[self.db_name].authenticate(self.user, self.password, auth_db)
  File "/opt/venv4archery/lib/python3.11/site-packages/pymongo/collection.py", line 3501, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists
```
```


### 版本

1.11.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

_No response_

**Comment by solomon-cc** [comment]
应该是pymongo从3.x升级4.x导致的，4.x认证方式变了

**Comment by sunbluers** [comment]
我使用的python3.9，也遇到相同的问题

**Comment by bwcxyk** [comment]
可以了吗

**Comment by huangsijun17** [comment]
连接mongo 7.0也有这一报错：
```
无法连接实例,
'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
```
