### ISSUE TITLE
command=gunicorn -w 4 -b 127.0.0.1:8888 --timeout 3600 archery.wsgi:application  timeout时间大于600时不生效

### ISSUE THREAD

**Issue by sunbluers** [hhyo/archer#2675]
### 重现步骤

SQL查询->在线查询->SQL查询，启动服务nginx和timeout时间均设置为3600

### 预期外的结果

当SQL执行大于600秒时，会提示错误并被中止：(3024, 'Query execution was interrupted, maximum statement execution time exceeded')

### 日志文本

错误信息Traceback (most recent call last):
  File "/export/data/archery-1.11.1/sql/engines/mysql.py", line 521, in query
    effect_row = cursor.execute(sql, parameters)
  File "/export/data/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/export/data/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
  File "/export/data/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
  File "/export/data/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
MySQLdb.OperationalError: (3024, 'Query execution was interrupted, maximum statement execution time exceeded')

### 版本

1.11.1

### 部署方式

手工部署

**Comment by nick2wang** [comment]
重复话题 #2674
