### ISSUE TITLE
sql上线工单状态一直在"执行中" ，但实际操作已经完成

### ISSUE THREAD

**Issue by Zzlllh** [hhyo/archer#2820]
### 重现步骤

通过helm安装好archery和goinception后，第一次上线mysql工单显示已完成，但后续上线全是确认中，实际操作已经完成
目前安装的两个环境都存在这个问题

### 预期外的结果

![Image_20240924134832](https://github.com/user-attachments/assets/c7972ff8-0954-4f85-a990-521bd8010b9c)

### 日志文本

```shell
2024-09-24 13:43:48,447 - django.request - WARNING - Forbidden (Permission denied): /admin/auth/group/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1929, in changelist_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied
```

### 版本

1.11.3

### 部署方式

K8S

**Comment by Zzlllh** [comment]
重启pod后问题解决了
应该是qcluster的问题

**Comment by Zzlllh** [comment]
后来发现这个问题是因为archery应该不支持redis 集群，用的redis proxy帮archery链接到redis集群，但是有一些操作redis proxy不支持导致卡住了，用了单独的redis问题解决

**Comment by 00yang** [comment]
我遇到了类似的情况， 我archery使用的mysql容器由于efs的问题卡住了。  选择备份sql的时候会出现“执行中”，实际sql执行成功， 不选择备份sql的话会执行成功。    后续重启mysql容器正常了
